--
--OCD-1897 Cleanup
-- * removing old ATL column from certified_product table
-- * as well as pending_certified_product table
--   * do we actually want to do this? 
--alter table openchpl.certified_product
--drop column if exists testing_lab_id;
--alter table openchpl.pendingcertified_product
--drop column if exists testing_lab_id;
--alter table openchpl.pendingcertified_product
--drop column if exists testing_lab_name;
-- DO NOT RUN THIS UNTIL AFTER THE MULTIPLE ATL STORY HAS BEEN DEPLOYED
