alter table openchpl.certification_result
drop column if exists attestation_answer cascade,
drop column if exists export_documentation cascade,
drop column if exists documentation_url cascade,
drop column if exists use_cases cascade;

alter table openchpl.certification_result
add column attestation_answer bool,
add column export_documentation varchar(1024),
add column documentation_url varchar(1024),
add column use_cases varchar(1024);

alter table openchpl.pending_certification_result
drop column if exists attestation_answer,
drop column if exists export_documentation,
drop column if exists documentation_url,
drop column if exists use_cases;

alter table openchpl.pending_certification_result
add column attestation_answer bool,
add column export_documentation varchar(1024),
add column documentation_url varchar(1024),
add column use_cases varchar(1024);

insert into openchpl.certification_criterion (certification_edition_id, number, title, last_modified_user) select 3, '170.315 (b)(10)', 'Clinical Information Export', -1
       where not exists (select * from openchpl.certification_criterion where number = '170.315 (b)(10)' and title = 'Clinical Information Export');
insert into openchpl.certification_criterion (certification_edition_id, number, title, last_modified_user) select 3, '170.315 (d)(12)', 'Encrypt Authentication Credentials', -1
       where not exists (select * from openchpl.certification_criterion where number = '170.315 (d)(12)' and title = 'Encrypt Authentication Credentials');
insert into openchpl.certification_criterion (certification_edition_id, number, title, last_modified_user) select 3, '170.315 (d)(13)', 'Multi-Factor Authentication', -1
       where not exists (select * from openchpl.certification_criterion where number = '170.315 (d)(13)' and title = 'Multi-Factor Authentication');
insert into openchpl.certification_criterion (certification_edition_id, number, title, last_modified_user) select 3, '170.315 (g)(10)', 'Standardized API for Patient and Population Services', -1
       where not exists (select * from openchpl.certification_criterion where number = '170.315 (g)(10)' and title = 'Standardized API for Patient and Population Services');


insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2a EP Stage 2', 'Patient Electronic Access: Eligible Professional', 'Required Test 2: Stage 2 Objective 8 Measure 1 ', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2a EP Stage 2');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2a EP Stage 3', 'Patient Electronic Access: Eligible Professional', 'Required Test 2: Stage 3 Objective 5 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2a EP Stage 3');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2a EC ACI Transition', 'Patient Electronic Access: Eligible Clinician ', 'Required Test 2: Promoting Interoperability Transition Objective 3 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2a EC ACI Transition');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2a EC ACI', 'Provide Patients Electronic Access to Their Health Information (formerly Patient Electronic Access): Eligible Clinician', 'Required Test 2: Promoting Interoperability Objective 3 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2a EC ACI');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2a EH/CAH Stage 2', 'Patient Electronic Access: Eligible Hospital/Critical Access Hospital', 'Required Test 2: Stage 2 Objective 8 Measure 1 ', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2a EH/CAH Stage 2');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2a EH/CAH Stage 3', 'Provide Patients Electronic Access to Their Health Information (formerly Patient Electronic Access): Eligible Hospital/Critical Access Hospital', 'Required Test 2: Stage 3 Objective 5 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2a EH/CAH Stage 3');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2c EP Stage 2', 'Patient Electronic Access: Eligible Professional', 'Required Test 2: Stage 2 Objective 8 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2c EP Stage 2');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2c EP Stage 3', 'Patient Electronic Access: Eligible Professional', 'Required Test 2: Stage 3 Objective 5 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2c EP Stage 3');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2c EC ACI Transition', 'Patient Electronic Access: Eligible Clinician ', 'Required Test 2: Promoting Interoperability Transition Objective 3 Measure 1 ', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2c EC ACI Transition');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2c EC ACI', 'Provide Patients Electronic Access to Their Health Information (formerly Patient Electronic Access): Eligible Clinician', 'Required Test 2: Promoting Interoperability Objective 3 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2c EC ACI');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2c EH/CAH Stage 2', 'Patient Electronic Access: Eligible Hospital/Critical Access Hospital', 'Required Test 2: Stage 2 Objective 8 Measure 1 ', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2c EH/CAH Stage 2');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT2c EH/CAH Stage 3', 'Provide Patients Electronic Access to Their Health Information (formerly Patient Electronic Access): Eligible Hospital/Critical Access Hospital', 'Required Test 2: Stage 3 Objective 5 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT2c EH/CAH Stage 3');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4a EP Stage 2', 'View, Download, or Transmit (VDT): Eligible Professional', 'Required Test 4: Stage 2 Objective 8 Measure 2 ', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4a EP Stage 2');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4a EP Stage 3', 'View, Download, or Transmit (VDT): Eligible Professional', 'Required Test 4: Stage 3 Objective 6 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4a EP Stage 3');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4a EC ACI Transition', 'View, Download, or Transmit (VDT): Eligible Clinician Group', 'Required Test 4: Promoting Interoperability Transition Objective 3 Measure 2 ', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4a EC ACI Transition');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4a EC ACI', 'View, Download, or Transmit (VDT):  Eligible Clinician', 'Required Test 4: Promoting Interoperability Objective 4 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4a EC ACI');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4a EH/CAH Stage 2', 'View, Download, or Transmit (VDT): Eligible Hospital/Critical Access Hospital', 'Required Test 4: Stage 2 Objective 8 Measure 2 ', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4a EH/CAH Stage 2');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4a EH/CAH Stage 3', 'View, Download, or Transmit (VDT): Eligible Hospital/Critical Access Hospital', 'Required Test 4: Stage 3 Objective 6 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4a EH/CAH Stage 3');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4c EP Stage 2', 'View, Download, or Transmit (VDT): Eligible Professional', 'Required Test 4: Stage 2 Objective 8 Measure 2 ', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4c EP Stage 2');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4c EP Stage 3', 'View, Download, or Transmit (VDT): Eligible Professional', 'Required Test 4: Stage 3 Objective 6 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4c EP Stage 3');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4c EC ACI Transition', 'View, Download, or Transmit (VDT):  Eligible Clinician', 'Required Test 4: Promoting Interoperability Transition Objective 3 Measure 2 ', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4c EC ACI Transition');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4c EC ACI', 'View, Download, or Transmit (VDT):  Eligible Clinician', 'Required Test 4: Promoting Interoperability Objective 4 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4c EC ACI');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4c EH/CAH Stage 2', 'View, Download, or Transmit (VDT): Eligible Hospital/Critical Access Hospital', 'Required Test 4: Stage 2 Objective 8 Measure 2 ', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4c EH/CAH Stage 2');
insert into openchpl.macra_criteria_map (criteria_id, value, name, description, removed, last_modified_user) select (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)'), 'RT4c EH/CAH Stage 3', 'View, Download, or Transmit (VDT): Eligible Hospital/Critical Access Hospital', 'Required Test 4: Stage 3 Objective 6 Measure 1', false, -1
       where not exists (select * from openchpl.macra_criteria_map where criteria_id = (select certification_criterion_id from openchpl.certification_criterion where number = '170.315 (g)(10)') and value = 'RT4c EH/CAH Stage 3');
