-- OCD-1935
-- Delete deprecated upload templates

update openchpl.upload_template_version as utv
set deleted = true
where utv.deprecated = true;

-- OCD-1955
-- Add triggers to soft-delete cascade when certified_product is deleted
ALTER TABLE openchpl.ehr_certification_id_product_map DROP COLUMN IF EXISTS deleted;
ALTER TABLE openchpl.ehr_certification_id_product_map ADD COLUMN deleted BOOLEAN NOT NULL default false;

CREATE OR REPLACE FUNCTION openchpl.certified_product_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE openchpl.certification_event as src SET deleted = NEW.deleted WHERE src.certified_product_id = NEW.certified_product_id;
    UPDATE openchpl.certification_result as src SET deleted = NEW.deleted WHERE src.certified_product_id = NEW.certified_product_id;
    UPDATE openchpl.certified_product_accessibility_standard as src SET deleted = NEW.deleted WHERE src.certified_product_id = NEW.certified_product_id;
    UPDATE openchpl.certified_product_qms_standard as src SET deleted = NEW.deleted WHERE src.certified_product_id = NEW.certified_product_id;
    UPDATE openchpl.certified_product_targeted_user as src SET deleted = NEW.deleted WHERE src.certified_product_id = NEW.certified_product_id;
    UPDATE openchpl.corrective_action_plan as src SET deleted = NEW.deleted WHERE src.certified_product_id = NEW.certified_product_id;
    UPDATE openchpl.cqm_result as src SET deleted = NEW.deleted WHERE src.certified_product_id = NEW.certified_product_id;
    UPDATE openchpl.ehr_certification_id_product_map as src SET deleted = NEW.deleted WHERE src.certified_product_id = NEW.certified_product_id;
    UPDATE openchpl.pending_certification_result_additional_software as src SET deleted = NEW.deleted WHERE src.certified_product_id = NEW.certified_product_id;
    UPDATE openchpl.surveillance as src SET deleted = NEW.deleted WHERE src.certified_product_id = NEW.certified_product_id;
    UPDATE openchpl.listing_to_listing_map as src SET deleted = NEW.deleted WHERE src.parent_listing_id = NEW.certified_product_id;
    UPDATE openchpl.listing_to_listing_map as src SET deleted = NEW.deleted WHERE src.child_listing_id = NEW.certified_product_id;
    RETURN NEW;
END;
$$ language 'plpgsql';
DROP TRIGGER IF EXISTS certified_product_soft_delete on openchpl.certified_product;
CREATE TRIGGER certified_product_soft_delete AFTER UPDATE on openchpl.certified_product FOR EACH ROW EXECUTE PROCEDURE openchpl.certified_product_soft_delete();

CREATE OR REPLACE FUNCTION openchpl.certification_result_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE openchpl.certification_result_additional_software as src SET deleted = NEW.deleted WHERE src.certification_result_id = NEW.certification_result_id;
    UPDATE openchpl.certification_result_g1_macra as src SET deleted = NEW.deleted WHERE src.certification_result_id = NEW.certification_result_id;
    UPDATE openchpl.certification_result_g2_macra as src SET deleted = NEW.deleted WHERE src.certification_result_id = NEW.certification_result_id;
    UPDATE openchpl.certification_result_test_data as src SET deleted = NEW.deleted WHERE src.certification_result_id = NEW.certification_result_id;
    UPDATE openchpl.certification_result_test_functionality as src SET deleted = NEW.deleted WHERE src.certification_result_id = NEW.certification_result_id;
    UPDATE openchpl.certification_result_test_procedure as src SET deleted = NEW.deleted WHERE src.certification_result_id = NEW.certification_result_id;
    UPDATE openchpl.certification_result_test_standard as src SET deleted = NEW.deleted WHERE src.certification_result_id = NEW.certification_result_id;
    UPDATE openchpl.certification_result_test_task as src SET deleted = NEW.deleted WHERE src.certification_result_id = NEW.certification_result_id;
    UPDATE openchpl.certification_result_test_tool as src SET deleted = NEW.deleted WHERE src.certification_result_id = NEW.certification_result_id;
    UPDATE openchpl.certification_result_ucd_process as src SET deleted = NEW.deleted WHERE src.certification_result_id = NEW.certification_result_id;
    UPDATE openchpl.optional_functionality_met as src SET deleted = NEW.deleted WHERE src.certification_result_id = NEW.certification_result_id;
    RETURN NEW;
END;
$$ language 'plpgsql';
DROP TRIGGER IF EXISTS certification_result_soft_delete on openchpl.certification_result;
CREATE TRIGGER certification_result_soft_delete AFTER UPDATE on openchpl.certification_result FOR EACH ROW EXECUTE PROCEDURE openchpl.certification_result_soft_delete();

CREATE OR REPLACE FUNCTION openchpl.corrective_action_plan_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE openchpl.corrective_action_plan_certification_result as src SET deleted = NEW.deleted WHERE src.corrective_action_plan_id = NEW.corrective_action_plan_id;
    UPDATE openchpl.corrective_action_plan_documentation as src SET deleted = NEW.deleted WHERE src.corrective_action_plan_id = NEW.corrective_action_plan_id;
    RETURN NEW;
END;
$$ language 'plpgsql';
DROP TRIGGER IF EXISTS corrective_action_plan_soft_delete on openchpl.corrective_action_plan;
CREATE TRIGGER corrective_action_plan_soft_delete AFTER UPDATE on openchpl.corrective_action_plan FOR EACH ROW EXECUTE PROCEDURE openchpl.corrective_action_plan_soft_delete();

CREATE OR REPLACE FUNCTION openchpl.cqm_result_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE openchpl.cqm_result_criteria as src SET deleted = NEW.deleted WHERE src.cqm_result_id = NEW.cqm_result_id;
    RETURN NEW;
END;
$$ language 'plpgsql';
DROP TRIGGER IF EXISTS cqm_result_soft_delete on openchpl.cqm_result;
CREATE TRIGGER cqm_result_soft_delete AFTER UPDATE on openchpl.cqm_result FOR EACH ROW EXECUTE PROCEDURE openchpl.cqm_result_soft_delete();

CREATE OR REPLACE FUNCTION openchpl.surveillance_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE openchpl.surveillance_requirement as src SET deleted = NEW.deleted WHERE src.surveillance_id = NEW.id;
    RETURN NEW;
END;
$$ language 'plpgsql';
DROP TRIGGER IF EXISTS surveillance_soft_delete on openchpl.surveillance;
CREATE TRIGGER surveillance_soft_delete AFTER UPDATE on openchpl.surveillance FOR EACH ROW EXECUTE PROCEDURE openchpl.surveillance_soft_delete();

CREATE OR REPLACE FUNCTION openchpl.surveillance_requirement_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE openchpl.surveillance_nonconformity as src SET deleted = NEW.deleted WHERE src.surveillance_requirement_id = NEW.id;
    RETURN NEW;
END;
$$ language 'plpgsql';
DROP TRIGGER IF EXISTS surveillance_requirement_soft_delete on openchpl.surveillance_requirement;
CREATE TRIGGER surveillance_requirement_soft_delete AFTER UPDATE on openchpl.surveillance_requirement FOR EACH ROW EXECUTE PROCEDURE openchpl.surveillance_requirement_soft_delete();

CREATE OR REPLACE FUNCTION openchpl.surveillance_nonconformity_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE openchpl.surveillance_nonconformity_document as src SET deleted = NEW.deleted WHERE src.surveillance_nonconformity_id = NEW.id;
    RETURN NEW;
END;
$$ language 'plpgsql';
DROP TRIGGER IF EXISTS surveillance_nonconformity_soft_delete on openchpl.surveillance_nonconformity;
CREATE TRIGGER surveillance_nonconformity_soft_delete AFTER UPDATE on openchpl.surveillance_nonconformity FOR EACH ROW EXECUTE PROCEDURE openchpl.surveillance_nonconformity_soft_delete();

CREATE OR REPLACE FUNCTION openchpl.certification_result_test_task_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE openchpl.test_task as src SET deleted = NEW.deleted WHERE src.test_task_id = NEW.test_task_id;
    RETURN NEW;
END;
$$ language 'plpgsql';
DROP TRIGGER IF EXISTS certification_result_test_task_soft_delete on openchpl.certification_result_test_task;
CREATE TRIGGER certification_result_test_task_soft_delete AFTER UPDATE on openchpl.certification_result_test_task FOR EACH ROW EXECUTE PROCEDURE openchpl.certification_result_test_task_soft_delete();

CREATE OR REPLACE FUNCTION openchpl.test_task_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE openchpl.test_task_participant_map as src SET deleted = NEW.deleted WHERE src.test_task_id = NEW.test_task_id;
    RETURN NEW;
END;
$$ language 'plpgsql';
DROP TRIGGER IF EXISTS test_task_soft_delete on openchpl.test_task;
CREATE TRIGGER test_task_soft_delete AFTER UPDATE on openchpl.test_task FOR EACH ROW EXECUTE PROCEDURE openchpl.test_task_soft_delete();

-- set transparency attestation URLs as requested by ICSA Labs
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA1.10.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA1.11.01.1.170321');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA1.12.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA1.13.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA1.14.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA1.15.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA1.16.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA1.17.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA1.18.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA1.19.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA1.20.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII1.10.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII1.11.01.1.170321');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII1.12.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII1.13.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII1.14.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII1.15.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII1.16.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII1.17.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII1.18.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII1.19.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII1.20.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA2.10.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA2.11.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA2.12.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA2.13.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA2.14.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA2.15.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA2.16.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA2.17.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA2.18.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA2.19.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII3.09.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII3.10.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII3.11.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII3.12.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII3.13.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII3.14.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII3.15.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII3.16.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII3.17.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII3.18.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA4.09.01.0.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA4.10.01.0.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA4.11.01.0.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA4.12.01.0.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA4.13.01.0.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA4.14.01.0.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA4.15.01.0.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA4.16.01.0.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA4.17.01.0.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FIA4.18.01.0.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII4.09.01.0.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII4.10.01.0.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII4.11.01.0.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII4.12.01.0.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII4.13.01.0.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII4.14.01.0.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII4.15.01.0.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII4.16.01.0.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII4.17.01.0.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FII4.18.01.0.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA3.10.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA3.11.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA3.12.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA3.13.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA3.14.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA3.15.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA3.16.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA3.17.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA3.18.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA3.19.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI3.10.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI3.11.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI3.12.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI3.13.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI3.14.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI3.15.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI3.16.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI3.17.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI3.18.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI3.19.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA2.15.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA2.16.01.1.170321');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA2.17.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA2.18.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA2.19.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA2.20.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA2.21.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA2.22.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA2.23.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA2.24.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEA2.25.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI2.15.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI2.16.01.1.170321');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI2.17.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI2.18.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI2.19.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI2.20.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI2.21.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI2.22.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI2.23.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI2.24.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HEI2.25.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PAA3.09.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PAA3.10.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PAI3.09.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PAI3.10.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI3.15.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI3.16.01.1.170321');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI3.17.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI3.18.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI3.19.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI3.20.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI3.21.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI3.22.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI3.23.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI3.24.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI3.25.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA5.15.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA5.16.01.1.170321');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA5.17.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA5.18.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA5.19.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA5.20.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA5.21.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA5.22.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA5.23.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA5.24.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA5.25.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI5.15.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI5.16.01.1.170321');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI5.17.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI5.18.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI5.19.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI5.20.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI5.21.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI5.22.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI5.23.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI5.24.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI5.25.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA1.15.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA1.16.01.1.170321');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA1.17.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA1.18.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA1.19.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA1.20.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA1.21.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA1.22.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA1.23.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA1.24.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA1.25.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI2.15.01.1.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI2.16.01.1.170321');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI2.17.01.1.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI2.18.01.1.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI2.19.01.1.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI2.20.01.1.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI2.21.01.1.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI2.22.01.1.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI2.23.01.1.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI2.24.01.1.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI2.25.01.1.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA4.09.01.0.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA4.10.01.0.170321');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA4.11.01.0.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA4.12.01.0.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA4.13.01.0.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA4.14.01.0.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA4.15.01.0.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA4.16.01.0.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA4.17.01.0.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA4.18.01.0.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POA4.19.01.0.170728');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI4.09.01.0.170320');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI4.10.01.0.170321');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI4.11.01.0.170327');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI4.12.01.0.170426');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI4.13.01.0.170510');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI4.14.01.0.170519');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI4.15.01.0.170608');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI4.16.01.0.170705');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI4.17.01.0.170711');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI4.18.01.0.170727');
update openchpl.certified_product as cp set transparency_attestation_url = 'https://www.cerner.com/cehrt-disclosure-information' where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.POI4.19.01.0.170728');

-- mark as deleted mis-uploaded listings
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FI01.21.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FI01.22.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FI01.23.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FI03.19.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FI03.20.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FI04.19.01.0.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FI04.20.01.0.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.FI04.21.01.0.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HE03.20.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HE03.21.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HE03.22.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HE02.26.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HE02.27.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.HE02.28.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.CE01.20.01.0.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.CE01.21.01.0.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PA03.11.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO03.27.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO03.28.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO03.29.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO05.26.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO05.27.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO05.28.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO02.26.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO02.27.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO04.28.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO04.20.01.0.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO04.21.01.0.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO04.22.01.0.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO08.12.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO08.13.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO08.14.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO08.15.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO08.16.01.1.171110');
update openchpl.certified_product as cp set deleted = true where cp.certified_product_id = (select cpd.certified_product_id from openchpl.certified_product_details as cpd where chpl_product_number = '14.07.07.1221.PO08.11.01.1.171110');
