--
-- OCD-2637 - update test functionalities
--

-- removing some
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9225 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9098 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9371 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9339 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9340 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8976 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9543 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9745 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9569 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9570 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9179 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9571 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9572 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9178 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9166 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9166 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9455 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9481 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9194 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9194 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9657 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9658 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9196 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9195 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9656 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9193 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9193 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9482 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9659 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9559 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8974 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9549 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9320 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9693 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9314 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9167 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9644 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9223 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9197 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9591 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9189 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9594 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9593 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9190 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9199 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9592 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9198 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9595 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8970 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9054 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9390 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8856 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8873 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8863 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9221 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9106 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8362 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8807 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9673 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9718 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9672 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8884 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9459 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9303 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9661 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9661 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 7966 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8481 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8511 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8878 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9401 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9733 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8969 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8969 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8328 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8328 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8852 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8852 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8967 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8967 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8871 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8871 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8968 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8968 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8329 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8500 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8853 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8872 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8499 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8499 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9646 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8874 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9636 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8539 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9262 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9635 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9235 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9580 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9234 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9579 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 8596 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9099 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9097 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9100 and cc.number = '170.315 (b)(2)' and tf.name='Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9744 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9048 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9555 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id = 9739 and cc.number = '170.315 (a)(13)' and tf.name='Optional: 170.315(a)(3)(ii) Include a "reason for order" field';

update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9318 and cc.number = '170.315 (g)(6)' and tf.name='Alternative: 170.315(b)(1)(ii)(A)(5)(i) Be notified of the errors produced';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9318 and cc.number = '170.315 (g)(6)' and tf.name='Ambulatory: 170.315(b)(1)(iii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9318 and cc.number = '170.315 (g)(8)' and tf.name='Alternative: 170.315(b)(1)(ii)(A)(5)(i) Be notified of the errors produced';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9318 and cc.number = '170.315 (g)(8)' and tf.name='Ambulatory: 170.315(b)(1)(iii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9318 and cc.number = '170.315 (g)(9)' and tf.name='Ambulatory: 170.315(b)(1)(iii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9318 and cc.number = '170.315 (g)(9)' and tf.name='Alternative: 170.315(b)(1)(ii)(A)(5)(i) Be notified of the errors produced';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9187 and cc.number = '170.315 (g)(6)' and tf.name='Alternative: 170.315(b)(1)(ii)(A)(5)(i) Be notified of the errors produced';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9187 and cc.number = '170.315 (g)(6)' and tf.name='Ambulatory: 170.315(b)(1)(iii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9187 and cc.number = '170.315 (g)(8)' and tf.name='Ambulatory: 170.315(b)(1)(iii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9187 and cc.number = '170.315 (g)(8)' and tf.name='Alternative: 170.315(b)(1)(ii)(A)(5)(i) Be notified of the errors produced';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9187 and cc.number = '170.315 (g)(9)' and tf.name='Ambulatory: 170.315(b)(1)(iii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information';
update only openchpl.certification_result_test_functionality as crtf set deleted = true from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9187 and cc.number = '170.315 (g)(9)' and tf.name='Alternative: 170.315(b)(1)(ii)(A)(5)(i) Be notified of the errors produced';

-- changing some
update only openchpl.certification_result_test_functionality as crtf set test_functionality_id = (select tf.test_functionality_id from openchpl.test_functionality tf where tf.number = '(b)(5)(i)(E)') from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9318 and cc.number = '170.315 (b)(5)' and tf.name='Optional: 170.315(b)(4)(vii)(A)(2) When the hour, minute, and second are associated with a date of birth the technology must demonstrate that the correct time zone offset is included';
update only openchpl.certification_result_test_functionality as crtf set test_functionality_id = (select tf.test_functionality_id from openchpl.test_functionality tf where tf.number = '(b)(5)(ii)(A)(5)(i)') from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9318 and cc.number = '170.315 (b)(5)' and tf.name='Ambulatory: 170.315(b)(4)(v) The reason for referral; and referring or transitioning provider''s name and office contact information';
update only openchpl.certification_result_test_functionality as crtf set test_functionality_id = (select tf.test_functionality_id from openchpl.test_functionality tf where tf.number = '(b)(5)(ii)(A)(5)(i)') from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9187 and cc.number = '170.315 (b)(5)' and tf.name='Optional: 170.315(b)(4)(vii)(A)(2) When the hour, minute, and second are associated with a date of birth the technology must demonstrate that the correct time zone offset is included';
update only openchpl.certification_result_test_functionality as crtf set test_functionality_id = (select tf.test_functionality_id from openchpl.test_functionality tf where tf.number = '170.102(13)(ii)(C)') from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =9187 and cc.number = '170.315 (b)(5)' and tf.name='Ambulatory: 170.315(b)(4)(v) The reason for referral; and referring or transitioning provider''s name and office contact information';
update only openchpl.certification_result_test_functionality as crtf set test_functionality_id = (select tf.test_functionality_id from openchpl.test_functionality tf where tf.number = '(b)(5)(i)(E)') from openchpl.test_functionality tf, openchpl.certification_result cr, openchpl.certification_criterion cc where crtf.test_functionality_id = tf.test_functionality_id and crtf.certification_result_id = cr.certification_result_id and cr.certification_criterion_id = cc.certification_criterion_id and cr.certified_product_id =8851 and cc.number = '170.315 (b)(5)' and tf.name='Ambulatory: 170.315(b)(4)(v) The reason for referral; and referring or transitioning provider''s name and office contact information';

-- cleanup
-- OCD-794
alter table openchpl.contact drop column if exists first_name;
alter table openchpl.contact drop column if exists last_name;

-- OCD-1739
DROP TABLE IF EXISTS openchpl.accurate_as_of_date;
ALTER TABLE openchpl.certified_product DROP COLUMN IF EXISTS meaningful_use_users;

--OCD-1897 Cleanup
-- * removing old ATL column from certified_product table
-- * as well as pending_certified_product table
alter table openchpl.certified_product
drop column if exists testing_lab_id;
alter table openchpl.pending_certified_product
drop column if exists testing_lab_id;
alter table openchpl.pending_certified_product
drop column if exists testing_lab_name;

--OCD-2532
ALTER TABLE openchpl.test_functionality DROP COLUMN IF EXISTS certification_criterion_id_deleted;
