--
-- OCD-2248: Bulk change InfoGard Listings Public Test Summary Report and UCD URLs
--

-- Update REPORT_FILE_LOCATION
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2392-R-0007-PRI%20V1.0%20GE%20Health%206.94.1%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-019344');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2392-R-0020-PRI%20V1.0%20GE%20Health%206.94.2%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-019627');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2392-R-0028-PRI%20V1.0%20GE%20Health%206.94.3%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-020508');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2623-R-0030-PRA%20V1.0%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-021723');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2623-R-0030-PRI%20V1.0%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-021724');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2936-R-0003-PRA%20V1.0%20FairWarning%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-019086');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2936-R-0003-PRI%20V1.0%20FairWarning%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-019087');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2936-R-0004-PRA%20V1.0%20FairWarning%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-019088');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2936-R-0004-PRI%20V1.0%20FairWarning%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-019089');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2967-R-0012-PRA-PEPID-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-019342');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2967-R-0012-PRI-PEPID-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-019343');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-2999-R-0022-PRA-Aprima-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-019694');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-3027-R-0014-PRA%20V1.0%20STC%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-019382');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-3095-R-0041-PRA%20V1.0%20Twistle%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-021728');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-3113-R-0036-PRA%20V1%200%20Micro_Office%20Systems%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-021433');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-3114-R-0038-PRA%20V1.0%20Azara%20Healthcare%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-021684');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/13-3143-R-0043-PRA%20V1.0%20Health%20Companion%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-021852');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2349-R-0088-PRA-MedA-Z-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025339');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2351-R-0019-PRA-CGM-webEHR-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022825');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2360-R-0005-PRA-DR-Systems-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022027');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2373-R-0085-PRA-Digital-Medical-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025050');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2384-R-0025-PRA-InfinittNA-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023619');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2388-R-0041-PRA-Dexter-Solutions-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023614');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2392-R-0003-PRI%20V1.0%20GE%20Health%206.95.0%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-021763');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2392-R-0012-PRI%20V1.0%20GE%20Health%206.95.1%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022108');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2392-R-0038-PRI%20V1.0%20GE%20Health%206.95.2%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023037');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2392-R-0070-PRI%20V1.0%20GE%20Health%206.95.3%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024533');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2403-R-0037-PRA-CMS-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023629');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2403-R-0080-PRA-CMS-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024643');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2412-R-0077-PRA-PracticeSuite-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024886');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2419-R-0018-PRA-IHS-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023620');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2419-R-0018-PRI-IHS-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023621');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2449-R-0011-PRI-Medsphere-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023139');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2449-R-0017-PRA-Medsphere-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022465');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2469-R-0004-PRA-ezEMRx-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022822');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2487-R-0029-PRA-Adaptamed-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022972');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2492-R-0042-PRA-drchrono-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023296');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2524-R-0083-PRA-Acurus-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027062');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2526-R-0010-PRA%20V1.0%20Software%20Partners%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022110');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2529-R-0075-PRA-Infinite-Software-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025318');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2536-R-0068-PRA-Connexin-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024493');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2552-R-0089-PRA-InstantDx-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024979');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2552-R-0089-PRI-InstantDx-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024980');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2556-R-0002-PRA%20V1.0%20i2i%20Systems%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-021800');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2577-R-0054-PRA-Green-Clinical-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024862');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2577-R-0054-PRI-Green-Clinical-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024863');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2578-R-0051-PRA-Softworx-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023899');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2592-R-0040-PRI-Meta-Healthcare-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023244');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2623-R-0030-PRA%20V1.0%20Stockell%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022847');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2623-R-0030-PRI%20V1.0%20Stockell%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022848');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2623-R-0031-PRA%20V1.0%20Stockell%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022845');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2623-R-0031-PRI%20V1.0%20Stockell%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022846');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2636-R-0014-PRA-eMedPractice-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022821');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2655-R-0079-PRA-TenEleven-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024745');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2655-R-0079-PRI-TenEleven-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024746');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2710-R-0024-PRA-V1.1-Data-Tec-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022971');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2710-R-0092-PRA-V1.1-Data-Tec-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025329');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2865-R-0048-PRA%20V1.0%20Bactes%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023361');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-2999-R-0047-PRA-Aprima-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023360');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3138-R-0008-PRA-Systemedx-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022218');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3149-R-0022-PRA-Penn-Medical-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022851');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3150-R-0013-PRA%20BioMed%20Informatics%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022849');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3150-R-0013-PRI%20BioMed%20Informatics%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022850');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3160-R-0009-PRA%20V1%200%20Splunk%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022490');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3160-R-0009-PRI%20V1.0%20Splunk%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022491');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3193-R-0053-PRA-MDops-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023902');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3199-R-0020-PRA-CGM-Clinical-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022823');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3200-R-0021-PRA-2014-CGM-Enterprise-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022824');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3201-R-0027-PRA%20V1.0%20LogRhythm%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022942');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3201-R-0027-PRI%20V1.0%20LogRhythm%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-022943');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3230-R-0072-PRA%20V1.0%20TPR%20Media%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024974');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3230-R-0072-PRI%20V1.0%20TPR%20Media%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024975');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3246-R-0057-PRA-WRS-Health-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024050');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3275-R-0055-PRA%20V1.0%20Signature%20Medical%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023632');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3279-R-0050-PRA%20V1.0%20Bearhug%20Technologies%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023630');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3279-R-0050-PRI%20V1.0%20Bearhug%20Technologies%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023631');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3282-R-0043-PRA-MD-On-Line-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023297');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3284-R-0036-PRI%20V1.0%20Health%20Companion%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-023036');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3306-R-0056-PRA-GeniusDoc-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024405');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3330-R-0087-PRA%20V1.0%20Wisconsin%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024849');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3355-R-0091-PRA-V1.0-Scribe-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025489');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3376-R-0093-PRA%20V1.0%20OEMR%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025005');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3385-R-0074-PRA%20V1.0%20PluralSoft%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024476');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3413-R-0096-PRA-NextServices-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025408');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3417-R-0086-PRA-V1.0-Relatient-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025330');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3439-R-0090-PRA%20V1.0%20Novobi%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024976');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/14-3439-R-0090-PRI%20V1.0%20Novobi%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-024977');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2376-R-0082-PRA-DocComply-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025096');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2392-R-0029-PRI-V1.0-GE-Health-6.96.0-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027140');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2392-R-0040-PRI-V1.0-GE-Healthcare-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028086');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2397-R-0049-PRA-Insight-Software-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028518');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2399-R-0005-PRA-UltraMed-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025409');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2453-R-0018-PRA-V1.0-Ebio-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.1388.A018.01.00.0.160906');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2506-R-0009-PRA-Emerald-Health-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-026060');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2561-R-0043-PRA-RTZ-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028331');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2585-R-0017-PRA-Streamline-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027122');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2585-R-0025-PRI-Streamline-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027703');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2623-R-0044-PRA-V1.0-Stockell-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028223');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2623-R-0044-PRI-V1.0-Stockell-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028224');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2654-R-0028-PRA-V1.0-Intuitive-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029176');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2654-R-0028-PRI-V1.0-Intuitive-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029177');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2697-R-0019-PRA-DrScribe-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-026059');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2763-R-0042-PRA-Goldblatt-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028391');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2824-R-0012-PRA-Krassons-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025376');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2936-R-0050-PRA-V1.0-FairWarning-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028594');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2936-R-0050-PRI-V1.0-FairWarning-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028595');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-2999-R-0048-PRA-Aprima-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028478');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3002-R-0007-PRA-Braintree-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-026012');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3002-R-0007-PRI-Braintree-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-026013');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3086-R-0027-PRA-Quantum-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028102');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3096-R-0002-PRA-Global-Vision-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028034');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3114-R-0026-PRA-V1.0-Azara-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027071');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3120-R-0030-PRI-Technomad-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028101');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3126-R-0052-PRA-V1.0-FIGmd-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028720');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3126-R-0052-PRI-V1.0-FIGmd-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028721');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3160-R-0022-PRA-V1.0-Splunk-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029014');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3160-R-0022-PRI-V1.0-Splunk-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029015');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3200-R-0038-PRA-CGM-Enterprise-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028298');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3201-R-0037-PRA-V1.0-LogRhythm-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027918');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3201-R-0037-PRI-V1.0-LogRhythm-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027919');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3251-R-0014-PRA-V1.0-PatientPoint-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025332');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3262-R-0036-PRA-WEBeDoctor-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028253');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3269-R-0006-PRA-Custom-Computing-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025410');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3281-R-0016-PRA-CareTracker-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025488');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3281-R-0045-PRA-V1.0-Harris-CareTracker-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028834');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3282-R-0024-PRA-Insync-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-026526');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3290-R-0039-PRA-V1.1-QuikEyes-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028366');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3292-R-0015-PRI-V1.0-GE-Health-6.95.5-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025331');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3330-R-0007-PRA-Wisconsin-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029159');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3332-R-0021-PRA-EndoSoft-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027123');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3332-R-0021-PRI-EndoSoft-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027124');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3332-R-0034-PRA-EndoSoft-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027648');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3332-R-0034-PRI-EndoSoft-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027649');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3345-R-0047-PRA-V1.0%20Tenzing%20EHR%20Public%20Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2936.A019.01.00.1.161109');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3345-R-0047-PRI-V1.0%20Tenzing%20EHR%20Public%20Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2936.A020.01.00.1.161109');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3350-R-0010-PRA-V1.0-ReportingMD-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025309');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3350-R-0054-PRA_V1.0_ReportingMD_PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028961');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3367-R-0001-PRA-V1.0-HealthGrid-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025374');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3367-R-0001-PRI-V1.0-HealthGrid-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025375');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3367-R-0033-PRA%20V1.0-Health-Grid-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027644');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3367-R-0033-PRI%20V1.0-Health-Grid-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027645');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3367-R-0041-PRA-V1.0-Health-Grid-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028087');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3367-R-0041-PRI-V1.0-Health-Grid-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028088');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3400-R-0032-PRA-Ensoftek-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027929');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3403-R-0003-PRA%20V1%200%20Hippoverse%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-025051');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3424-R-0013-PRA-DataGroup-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027704');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3449-R-0031-PRA-Panacea-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027988');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3478-R-0051-PRA-V1.0-Health-eFilings-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028603');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3487-R-0020-PRA-V1.0-Siemens-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027526');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3487-R-0020-PRI-V1.0-Siemens-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-027527');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3498-R-0035-PRA-V1.0-ZH-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028960');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3538-R-0055-PRA-V1.1-MedTrio-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2646.A001.01.00.1.160412');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3545-R-0053-PRI-V1.0-Strateq-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028979');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3584-R-0046-PRA-V1.0-Bottomline-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028275');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/15-3584-R-0046-PRI-V1.0-Bottomline-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-028276');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16%E2%80%903598%E2%80%90R%E2%80%900009-PRA-V1.0-Viztek-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029210');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16%E2%80%903721%E2%80%90R%E2%80%900003-PRA-V1.0-EnableDoc-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029160');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2384-R-0008-PRA-V1.0-InfinittNA-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029175');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2392-R-0013-PRI-GE-Healthcare.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2902.A003.01.01.1.160503');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2392-R-0028-PRI-V1.0-GE-Healthcare.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2902.A003.02.01.1.160929');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2423-R-0022-PRI%20V1.0%20Picis%20ED%20PulseCheck%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2926.A011.01.01.1.160620');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2423-R-0023-PRI%20V1.0%20Picis%20ED%20PulseCheck%20PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2926.A011.02.01.1.160620');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2423-R-0024-PRI-V1.0-Picis-PulseCheck-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2926.A011.03.01.1.160708');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2563-R-0006-PRA-V1.0-eHealthObjects-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029178');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2592-R-0017-PRI-V1.0-Meta-Healthcare-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.1978.A038.01.01.1.170410');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2623-R-0015-PRA-V1.0-Stockell-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2376.A004.01.01.1.160523');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2623-R-0015-PRI-V1.0-Stockell-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2376.A005.01.01.1.160523');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2623-R-0016-PRA-V1.0-Medsphere-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2376.A006.01.01.1.160523');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2623-R-0016-PRI-V1.0-Medsphere-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2376.A007.01.01.1.160523');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2651-R-0004-PRA-V1.0-Medi-EHR-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029161');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2763-R-0005-PRA-V1.0-Goldblatt-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029044');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2860-R-0012-PRA-V1.0-Webconsort-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2531.A008.01.00.0.160620');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-2999-R-0033-PRA-V1.0-Aprima-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2968.A027.01.01.1.170110');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3027-R-0026-PRA-V1.0-STC.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2309.A012.01.00.0.170616');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3245-R-0037-PRI-V1.0-Picis-PulseCheck-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2926.A011.04.01.1.170109');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3265-R-0039-PRA-V1.0-Life%20Systems-2014.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.1799.A024.01.00.1.170208');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3356-R-0010-PRA-V1.0-DermWrite-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2659.A002.01.00.1.160506');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3376-R-0040-PRA-OEMR-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2080.A032.01.01.1.170213');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3494-R-0031-PRI-V1.0-Callibra-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.1192.A022.01.00.1.161128');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3528-R-0027-PRA-V1.1-PatientClick-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2141.A017.01.00.1.161019');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3560-R-0014-PRA-V1.1-UPMC-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2654.A009.01.00.0.160614');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3560-R-0014-PRI-V1.1-UPMC-PRI.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2654.A010.01.00.0.160614');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3687-R-0001-PRA-V1.0-OSEHRA-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029006');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3687-R-0001-PRI-V1.0-OSEHRA-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-029007');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3811-R-0018-PRI-V1.0-Picis-v8.6-OR-Manager.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2926.A013.01.01.0.161010');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3811-R-0019-PRI-V1.0-Picis-v8.6-PACU-Manager.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2926.A014.01.01.0.161010');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3811-R-0020-PRI-V1.0-Picis-v8.6-Anesthesia-Manager.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2926.A015.01.01.0.161010');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3811-R-0021-PRI-V1.0-Picis-v8.6-Critical-Care-Manager.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2926.A016.01.01.0.161010');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/16-3851-R-0029-PRA-V1.0-NJH-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2937.A021.01.00.1.161111');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-2350-R-0003-PRA-V1.0-Paramount-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2131.A037.01.00.1.170420');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-2392-R-0013-PRI-V1.0-GE-Healthcare-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2902.A003.03.01.1.170511');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-2392-R-0024-PRI-V1.0-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2902.A003.04.02.1.171130');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-2453-R-0005-PRA-EBIO-Functionality-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.1388.A031.01.01.0.170130');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-2505-R-0006-PRA-ASP.MD-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.1026.A033.01.01.0.170217');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-2999-R-0002-PRA-V1.0-Aprima-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2968.A027.02.01.1.170117');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-2999-R-0009-PRA-Aprima-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2968.A027.03.01.1.170306');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-3199-R-0022-PRA-V1.0-CGM-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2700.A047.02.01.1.171117');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-3200-R-0021-PRA-V1.0-CGM-Enterprise-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2700.A052.03.01.1.180117');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-3529-R-0015-PRA-V1.0-OHS-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2102.A041.01.00.1.170621');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-3793-R-0001-PRA-V1.0-Orb-Health-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2948.A028.01.00.0.170119');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/17-3923-R-0008-PRA-Physician-Compass-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2955.A035.01.01.0.170306');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/18-2556-R-0014-PRA-V1.0-i2i-Pop-Health-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2616.A060.01.01.0.180320');
update openchpl.certified_product set report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/18-3923-R-0016-PRA-V1.0-Phys-Compass-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '14.02.02.2955.A035.02.02.0.180406');
update openchpl.certified_product set report_file_location = 'https://industries.ul.com/wp-content/uploads/sites/2/2018/05/13-2397-R-0027-PRA-Insight-PTR.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = 'CHP-020598');

-- Update SED_REPORT_FILE_LOCATION
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/Arete-SED-Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.02.02.1112.A062.01.00.1.180320');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/ATG-EHR-10-SED.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.05.02.2670.A048.01.00.1.171206');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/Capella-EHR-6.1-SED-Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.02.02.2669.A067.01.00.1.180411');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/Complete-Medical-4.0-SED-Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.05.02.1272.A061.01.00.1.180320');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/DOX-EMR-5.2.0-SED-Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.02.02.1317.A059.01.00.1.180315');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/EHealthLine-CARE-SED-Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.02.02.1384.A065.01.00.0.180406');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/EHealthLine-Phoenix-SED-Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.02.02.1384.A064.01.00.0.180406');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/eMedicalPractice%20v2.0%20SED%20Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.02.02.2898.A042.01.00.1.170929');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/eNotes_4.1_SED_Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.02.02.2600.A026.01.00.0.170105');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/MDToolbox-UCD.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.05.02.1832.A045.01.00.1.171102');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/MVE_v2018_UCD_Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.02.02.1703.A057.01.00.1.180301');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/NovoClinical-1.0-SED-Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.02.02.3015.A066.01.00.1.180410');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/PracticeSuite-18-SED-Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.02.02.2198.A058.01.00.1.180306');
update openchpl.certified_product set sed_report_file_location = 'http://connect.ul.com/rs/365-LEA-623/images/TRIARQ-QSuite-Usability-Test-Report.pdf' where certified_product_id =  (select certified_product_id from openchpl.certified_product_details where chpl_product_number = '15.02.02.2614.A053.01.00.1.180123');


--
-- OCD-2226: Clean up Test Tools
--

-- Consolidate all Direct Certificate Discovery Tool + 2015 Direct Certificate Discovery Tool to "Direct Certificate Discovery Tool"
update openchpl.test_tool tt
set deleted = true
where tt.test_tool_id > (select min(test_tool_id) from openchpl.test_tool tt where tt.name like '%Direct Certificate Discovery Tool%' and tt.deleted = false)
and tt.name like '%Direct Certificate Discovery Tool%';

update openchpl.certification_result_test_tool
set test_tool_id = (select min(test_tool_id) from openchpl.test_tool tt where tt.name like '%Direct Certificate Discovery Tool%' and tt.deleted = false)
where test_tool_id = any(select test_tool_id from openchpl.test_tool tt where tt.name like '%Direct Certificate Discovery Tool%' and tt.deleted = true);

update openchpl.pending_certification_result_test_tool
set test_tool_id = (select min(test_tool_id) from openchpl.test_tool tt where tt.name like '%Direct Certificate Discovery Tool%' and tt.deleted = false)
where test_tool_id = any(select test_tool_id from openchpl.test_tool tt where tt.name like '%Direct Certificate Discovery Tool%' and tt.deleted = true);

-- Consolidate HL7 v2 Electronic Laboratory Reporting (ELR) Validation Tool (x2) and HL7 v2 Electronic Laboratory Reporting Validation Tool to "HL7 v2 Electronic Laboratory Reporting (ELR) Validation Tool"
update openchpl.test_tool tt
set deleted = true
where tt.test_tool_id > (select min(test_tool_id) from openchpl.test_tool tt where tt.name like '%Electronic Laboratory Reporting%' and tt.deleted = false)
and tt.name like '%Electronic Laboratory Reporting%';

update openchpl.certification_result_test_tool
set test_tool_id = (select min(test_tool_id) from openchpl.test_tool tt where tt.name like '%Electronic Laboratory Reporting%' and tt.deleted = false)
where test_tool_id = any(select test_tool_id from openchpl.test_tool tt where tt.name like '%Electronic Laboratory Reporting%' and tt.deleted = true);

update openchpl.pending_certification_result_test_tool
set test_tool_id = (select min(test_tool_id) from openchpl.test_tool tt where tt.name like '%Electronic Laboratory Reporting%' and tt.deleted = false)
where test_tool_id = any(select test_tool_id from openchpl.test_tool tt where tt.name like '%Electronic Laboratory Reporting%' and tt.deleted = true);

-- "Electronic Prescribing" + "ePrescribing Validation Tool" = "Electronic Prescribing"
update openchpl.test_tool tt
set deleted = true
where tt.test_tool_id = 1;

update openchpl.certification_result_test_tool
set test_tool_id = 13
where test_tool_id = 1;

update openchpl.pending_certification_result_test_tool
set test_tool_id = 13
where test_tool_id = 1;

-- "Transport Test Tool" + "Transport Testing Tool" = "Transport Testing Tool"
update openchpl.test_tool tt
set deleted = true
where tt.test_tool_id = 15;

update openchpl.certification_result_test_tool
set test_tool_id = 7
where test_tool_id = 15;

update openchpl.pending_certification_result_test_tool
set test_tool_id = 7
where test_tool_id = 15;

-- "Healthcare Associated Infections (HAI) Validator" -> CDC's NHSN CDA Validator
-- "Edge Test Tool" -> "Edge Testing Tool"
update openchpl.test_tool tt
set name = 'CDC''s NHSN CDA Validator'
where test_tool_id = 24;
update openchpl.test_tool tt
set name = 'Edge Testing Tool'
where test_tool_id = 16;

----
-- OCD-2260 - Add new activity concept and change relevant activity
--

INSERT INTO openchpl.activity_concept(
	activity_concept_id, concept, last_modified_user)
--cannot use the bigserial sequence here because all preloaded concepts declared the ID
SELECT 15, 'CORRECTIVE_ACTION_PLAN', -1 
	WHERE NOT EXISTS (SELECT 1 FROM openchpl.activity_concept WHERE concept = 'CORRECTIVE_ACTION_PLAN');
	
UPDATE openchpl.activity
SET activity_object_concept_id = (SELECT activity_concept_id FROM openchpl.activity_concept where concept = 'CORRECTIVE_ACTION_PLAN')
WHERE UPPER(description) LIKE '%CORRECTIVE ACTION PLAN%';

--
-- OCD-2104: new vs. incumbent statistics
--
DROP TABLE IF EXISTS openchpl.incumbent_developers_statistics;
CREATE TABLE openchpl.incumbent_developers_statistics (
        id bigserial NOT NULL,
        new_count bigint NOT NULL,
        incumbent_count bigint NOT NULL,
        old_certification_edition_id bigint NOT NULL,
        new_certification_edition_id bigint NOT NULL,
        creation_date timestamp without time zone NOT NULL DEFAULT now(),
        last_modified_date timestamp without time zone NOT NULL DEFAULT now(),
        last_modified_user bigint NOT NULL,
        deleted boolean NOT NULL DEFAULT false,
        CONSTRAINT incumbent_developers_statistics_pk PRIMARY KEY (id),
        CONSTRAINT old_certification_edition_fk FOREIGN KEY (old_certification_edition_id)
        REFERENCES openchpl.certification_edition (certification_edition_id) MATCH FULL
        ON DELETE RESTRICT ON UPDATE CASCADE,
        CONSTRAINT new_certification_edition_fk FOREIGN KEY (new_certification_edition_id)
        REFERENCES openchpl.certification_edition (certification_edition_id) MATCH FULL
        ON DELETE RESTRICT ON UPDATE CASCADE
        );
CREATE TRIGGER incumbent_developers_statistics_audit AFTER INSERT OR UPDATE OR DELETE on openchpl.incumbent_developers_statistics FOR EACH ROW EXECUTE PROCEDURE audit.if_modified_func();
CREATE TRIGGER incumbent_developers_statistics_timestamp BEFORE UPDATE on openchpl.incumbent_developers_statistics FOR EACH ROW EXECUTE PROCEDURE openchpl.update_last_modified_date_column();
--re-run grants
\i dev/openchpl_grant-all.sql
