-- Test standard updates (OCD-1840)
\! echo "Updating"
update openchpl.test_standard as ts set number = '(b)(1)(iii)(B):170.207(a)(4); "Assessment Section (V2)" and "Plan of Treatment Section (V2)" of the standard specified in 170.205(a)(4).' where ts.number like '(b)(1)(iii)(B):170.207(a)(4);  "Assessment Section (V2)" and "Plan of Treatment Section (V2)" of the standard specified in _ 170.205(a)(4).';
update openchpl.test_standard as ts set number = '(b)(4)(ii)(A); 170.207(a)(4)' where ts.number = '(b)(4)(ii)(A) 170.207(a)(4)';
update openchpl.test_standard as ts set number = '(b)(6)(ii)(B): 170.207(a)(4); Optional CCDS: 170.207(a)(4); "Assessment Section (V2)" and "Plan of Treatment Section (V2)" of the standard specified in 170.205(a)(4).' where ts.number like '(b)(6)(ii)(B): 170.207(a)(4);Optional CCDS: 170.207(a)(4);  "Assessment Section (V2)" and "Plan of Treatment Section (V2)" of the standard specified in _ 170.205(a)(4).';
update openchpl.test_standard as ts set number = '(e)(1)(i): 170.204(a)(1); Optional CCDS: 170.207(a)(4); "Assessment Section (V2)" and "Plan of Treatment Section (V2)" of the standard specified in 170.205(a)(4).' where ts.number like '(e)(1)(i): 170.204(a)(1);Optional CCDS: 170.207(a)(4); "Assessment Section (V2)" and "Plan of Treatment Section (V2)" of the standard specified in _ 170.205(a)(4).';
update openchpl.test_standard as ts set number = '(e)(1)(i): 170.204(a)(2); CCDS: 170.207(b)(2)' where ts.number = '(e)(1)(i): 170.204(a)(2);CCDS: 170.207(b)(2)';
update openchpl.test_standard as ts set number = '(e)(1)(ii)(A)(2): 170.210(g) NTP v4' where ts.number = '(e)(1)(ii)(A)(2):170.210(g) NTPv4';
update openchpl.test_standard as ts set number = '(f)(5)(iii)(B)(2): 170.207(a)(4); Assessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)' where ts.number = '(f)(5)(iii)(B)(2) 170.207(a)(4); Assessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)';
update openchpl.test_standard as ts set number = '170.202(a)(2); 170.202(b); 170.202(d); 170.202(e)(1)' where ts.number = '170.202(a)(2);  170.202(b);170.202(d); 170.202(e)(1)';
update openchpl.test_standard as ts set number = '170.205(h)(2)' where ts.number = '170.205 (h)(2)';
update openchpl.test_standard as ts set number = '170.205(k)(1)' where ts.number = '170.205 (k)(1)';
update openchpl.test_standard as ts set number = '170.205(k)(2)' where ts.number = '170.205 (k)(2)';
update openchpl.test_standard as ts set number = '170.205(a)(4); 170.205(o)(1)' where ts.number = '170.205(a)(4);  170.205(o)(1)';
update openchpl.test_standard as ts set number = '170.205(i)(2); 170.207(a)(4); 170.207(c)(3)' where ts.number = '170.205(i)(2); 170.207(a)(4);  170.207(c)(3)';
update openchpl.test_standard as ts set number = '170.207(a)(4); 170.207(b)(2); Assessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)' where ts.number = '170.207(a)(4);  170.207(b)(2); Assessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)';
update openchpl.test_standard as ts set number = '170.205(a)(3); 170.205(a)(4); 170.207(a)(4)' where ts.number = '170.207(a)(4); 170.205(a)(4);170.205(a)(3)';
update openchpl.test_standard as ts set number = '170.207(f)(2) CDC Race and Ethnicity' where ts.number like '170.207(f)(2) CDC Race and Ethnicity_Code Set Version 1.0 (March 2000)';
update openchpl.test_standard as ts set number = '170.207(f)(1); 170.207(f)(2); 170.207(g)(2); 170.207(o)(1)' where ts.number = '170.207(f)(2);  170.207(f)(1); 170.207(g)(2);70.207(o)(1)';
update openchpl.test_standard as ts set number = '170.207(h)(2); 170.207(k)(2); 170.207(f)(2); 170.207(n)(1); 170.207(r)(1); 170.207(s)(1)' where ts.number = '170.207(f)(2); 170.207(n)(1); 170.207(r)(1); 170.207(s)(1);170.207(s)(1); 170.205(k)(2); 170.205(h)(2)';
update openchpl.test_standard as ts set number = '170.207(f)(1); 170.207(f)(2); 170.207(g)(2); 170.207(n)(1); 170.207(o)(1)' where ts.number = '170.207(f)(2);170.207(f)(1);170.207(g)(2);170.207(n)(1);170.207(o)(1)';
update openchpl.test_standard as ts set number = '170.207(f)(1); 170.207(f)(2); 170.207(o)(1)' where ts.number = '170.207(f)(2);170.207(f)(1);170.207(o)(1)';
update openchpl.test_standard as ts set number = '170.207(f)(1); 170.207(f)(2); 170.207(g)(2); 170.207(n)(1); 170.207(o)(1); 170.207(o)(2)' where ts.number = '170.207(g)(2); 170.207(f)(1); 170.207(f)(2); 170.207(n)(1); 170.207(o)(1); 170.207(o)(2)';
update openchpl.test_standard as ts set number = '170.207(a)(4); 170.207(b)(2); 170.207(i); Assessment and Plan Section (V2) of the standard specified in 170.205(a)(4)' where ts.number = '170.207(i);  170.207(a)(4);   170.207(b)(2); Assessment and Plan Section (V2) of the standard specified in 170.205(a)(4)';
update openchpl.test_standard as ts set number = '170.207(b)(2); 170.207(i); Assessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)' where ts.number = '170.207(i); 170.207(b)(2); Assessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)';
update openchpl.test_standard as ts set number = '170.210(g) RFC 1305 (NTP v3) -OR- RFC 5905 (NTP v4)' where ts.number = '170.210(g) RFC 1305  (NTP V3) -OR- RFC 5905 (NTP V4)';
update openchpl.test_standard as ts set number = '170.210(g) RFC 1305 (NTP v3)' where ts.number = '170.210(g) RFC 1305 [NTPv3]';
update openchpl.test_standard as ts set number = '170.210(g) RFC 5905 (NTP v4)' where ts.number = '170.210(g) RFC 5905 (NTP V4)';
update openchpl.test_standard as ts set number = '170.210(g) RFC 5905 (NTP v4); 170.210(h)' where ts.number = '170.210(g) RFC 5905 (NTP V4); 170.210(h)';
update openchpl.test_standard as ts set number = '(a)(4)(iii)' where ts.number = 'a(4)iii';
update openchpl.test_standard as ts set number = 'Data Elements and Vocabularies applicable to the Common Clinical Data Set (CCDS)' where ts.number = 'Data Elements and Vocabularies applicable to the Common Clinical Data Set';
update openchpl.test_standard as ts set number = 'Exchange Standards:
NCPDP SCRIPT Standard, Implementation Guide, Version 10.6 (incorporated by reference in 170.299).
Vocabulary Standards:
RxNorm, a standardized nomenclature for clinical drugs produced by the United States National Library of Medicine, August 6, 2012 Release (incorporated by reference in 170.299).' where ts.number like 'Exchange Standards:_NCPDP SCRIPT Standard, Implementation Guide, Version 10.6 (incorporated by reference in _170.299)._Vocabulary Standards:_RxNorm, a standardized nomenclature for clinical drugs produced by the United States National Library of Medicine, August 6, 2012 Release (incorporated by reference in _170.299).';
update openchpl.test_standard as ts set number = 'HL7 Implementation Guide for CDA Release 2' where ts.number like 'HL7 Implementation Guide for CDA_ Release 2';
update openchpl.test_standard as ts set number = 'HL7 Implementation Guide for CDA Release 2: Quality Reporting Document Architecture.
Quality Reporting Document Architecture Category III, Implementation Guide for CDA Release 2.
Health Level Seven Clinical Document Architecture (CDA) Release 2, Continuity of Care Document (CCD).
ASTM E2369 Standard Specification for Continuity of Care Record and Adjunct to ASTM E2369.' where ts.number like 'HL7 Implementation Guide for CDA_ Release 2: Quality Reporting Document Architecture._Quality Reporting Document Architecture Category III, Implementation Guide for CDA Release 2._Health Level Seven Clinical Document Architecture (CDA) Release 2, Continuity of Care Document (CCD)._ASTM E2369 Standard Specification for Continuity of Care Record and Adjunct to ASTM E2369.';
update openchpl.test_standard as ts set number = 'IHTSDO SNOMED CT International Release July 2012 (incorporated by reference in 170.299) and US Extension to SNOMED CT March 2012 Release (incorporated by reference in 170.299).' where ts.number like 'IHTSDO SNOMED CT_ International Release July 2012 (incorporated by reference in _170.299) and US Extension to SNOMED CT_ March 2012 Release (incorporated by reference in _170.299).';
update openchpl.test_standard as ts set number = 'ISO 13485 Medical Devices Quality Management Systems Requirements for Regulatory Purposes Standards as well as the FDA Quality System Regulation 21 CFR Part 820 and IEC 62366-1 Application of Usability Engineering to Medical Devices' where ts.number like 'ISO 13485 Medical Devices _ Quality Management Systems _ Requirements for Regulatory Purposes Standards as well as the FDA Quality System Regulation 21 CFR Part 820 and IEC 62366-1 Application of Usability Engineering to Medical Devices';
update openchpl.test_standard as ts set number = 'National Institute of Standards and Technology, http://csrc.nist.gov/groups/STM/cmvp/standards.html
Annex A: Approved Security Functions for FIPS PUB 140-2, Security Requirements for Cryptographic Modules, Draft, January 27, 2010, IBR approved for 170.210.' where ts.number like 'National Institute of Standards and Technology, http://csrc.nist.gov/groups/STM/cmvp/standards.html_Annex A: Approved Security Functions for FIPS PUB 140-2, Security Requirements for Cryptographic Modules, Draft, January 27, 2010, IBR approved for _170.210.';

\! echo "Deleting - not in cfr"
update openchpl.test_standard as ts set deleted = true where ts.number = '170.205(g)(3)';

\! echo "Removing"
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(a)(13)(i): 170.204(b)(4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(a)(13)(i) 170.204(b)(4)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(b)(1)(iii)(B): 170.207(a)(4); CCDS: 170.207(a)(4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(b)(1)(iii)(B): 170.207(a)(4);CCDS: 170.207(a)(4)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(b)(1)(iii)(B):170.207(a)(4); "Assessment Section (V2)" and "Plan of Treatment Section (V2)" of the standard specified in 170.205(a)(4).') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number like '(b)(1)(iii)(B):170.207(a)(4);  "Assessment Section (V2)_ and _Plan of Treatment Section (V2)_ of the standard specified in _ 170.205(a)(4).');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(b)(1)(iii)(B): 170.207(a)(4); CCDS: 170.207(a)(4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(b)(1)(iii)(B):170.207(a)(4);CCDS: 170.207(a)(4)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(b)(6)(ii)(B): 170.207(a)(4); Optional CCDS: 170.207(a)(4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(b)(6)(ii)(B): 170.207(a)(4);CCDS: 170.207(a)(4)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e)(1)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number LIKE '(e) Record actions related to electronic health information, audit log status, and encryption of end-user devices._(1)(i) The audit log must record the information specified in sections 7.2 through 7.4, 7.6, and 7.7 of the standard specified at _ 170.210(h) when EHR technology is in use._(ii) The date and time must be recorded in accordance with the standard specified at _ 170.210(g)._(2)(i) The audit log must record the information specified in sections 7.2 and 7.4 of the standard specified at _ 170.210(h) when the audit log status is changed._(ii) The date and time each action occurs in accordance with the standard specified at _ 170.210(g)._(3)The audit log must record the information specified in sections 7.2 and 7.4 of the standard specified at _ 170.210(h) when the encryption status of electronic health information locally stored by EHR technology on end-user devices is changed. The date and time each action occurs in accordance with the standard specified at _ 170.210(g)._170.210(g) Synchronized clocks. The date and time recorded utilize a system clock that has been synchronized following (RFC 1305) Network Time Protocol, (incorporated by reference in _ 170.299) or (RFC 5905) Network Time Protocol Version 4, (incorporated by reference in _ 170.299)._170.210(h) Audit log content. ASTM E2147-01 (Reapproved 2009), (incorporated by reference in _ 170.299)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e)(1)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number LIKE '(e)(1) Record actions related to electronic health information, audit log status, and encryption of end-user devices. (i) The audit log must record the information specified in sections 7.2 through 7.4, 7.6, and 7.7 of the standard specified at _170.210(h) when EHR technology is in use._(ii) The date and time must be recorded in accordance with the standard specified at _170.210(g)._(e)(2) (i) The audit log must record the information specified in sections 7.2 and 7.4 of the standard specified at _170.210(h) when the audit log status is changed. (ii) The date and time each action occurs in accordance with the standard specified at _170.210(g)._(e)(3)The audit log must record the information specified in sections 7.2 and 7.4 of the standard specified at _170.210(h) when the encryption status of electronic health information locally stored by EHR technology on end-user devices is changed. The date and time each action occurs in accordance with the standard specified at _170.210(g)._170.210(g) Synchronized clocks. The date and time recorded utilize a system clock that has been synchronized following (RFC 1305) Network Time Protocol, (incorporated by reference in _170.299) or (RFC 5905) Network Time Protocol Version 4, (incorporated by reference in _170.299)._170.210(h) Audit log content. ASTM E2147-01 (Reapproved 2009), (incorporated by reference in _170.299)"');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(e)(1)(i): 170.204(a)(1); Optional CCDS: 170.207(a)(4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(e)(1)(i): 170.204(a)(1);CCDS: 170.207(a)(4)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(e)(1)(i): 170.204(a)(1); Optional CCDS: 170.207(a)(4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(e)(1)(i): 170.204(a)(1);Optional CCDS: 170.207(a)(4);');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(e)(1)(ii)(A)(2):170.210(g) NTP v4') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(e)(1)(ii)(A)(2): 170.210(g)  NTPv4');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'Global Medical Device Nomenclature (GMDN)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '(GMDN)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.202(a)(2); 170.202 (e)(1)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.202 (e)(1); 170.202 (a)(2)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(a)(4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(a)(4');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(b)(2); 170.207(d)(3)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(b)(2), 170.207(d)(3)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(h)(2); 170.205(k)(1); 170.205(k)(2)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(h)2; 170.205(k)1;170.205(k)2');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(i)(2); 170.207(a)(4); 170.207(c)(3)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(i)(2);170.207(a)(4);170.207(c)(3)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(h)(2); 170.205(k)(1); 170.205(k)(2)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(k)(1); 170.205(k)(2); 170.205(h)(2)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(a)(4); 170.205(o)(1)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.205(o)(1); 170.205(a)(4)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(a)(4); Assessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(a)(4);  Assessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(a)(4); Assessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(a)(4); ssessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(a)(4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(a)4');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(b)(2); Assessment and Plan Section (V2) of the standard specified in 170.205(a)(4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(b)(2) Assessment and Plan Section (V2) of the standard specified in 170.205(a)(4)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(f)(2) CDC Race and Ethnicity') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(f)(2)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(f)(2) CDC Race and Ethnicity') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(f)(2) CDC Rance and Ethnicity Version 1.0 (September 2016)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(f)(1); 170.207(f)(2); 170.207(g)(2); 170.207(n)(1); 170.207(o)(1)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(f)2; 170.207(f)1; 170.207(g)2; 170.207(n)1; 170.207(o)1');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(a)(2)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(a)(2');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e)(1); 170.210(e)(2); 170.210(e)(3); 170.210(g); 170.210(h)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e)(1)(2)(3); 170.210(g); 170.210(h)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e)(1); 170.210(e)(2); 170.210(e)(3); 170.210(g)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e)(1); 170.210(e)(2);70.210(e)(3):70.210(g);');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e)(1); 170.210(e)(2); 170.210(e)(3); 170.210(g); 170.210(h)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e)(1);(2);(3); 170.201(g);(h)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e); 170.210(g); 170.210(h)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e);170.210(g) ; 170.210(h)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(f)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number like '170.210(f)_');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 1305 (NTP v3)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) NTP v3');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 5905 (NTP v4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) NTP v4');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 1305 (NTP v3)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) NTPv3');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 5905 (NTP v4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) NTPv4');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 1305 (NTP v3)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 1305  (NTP V3)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 1305 (NTP v3)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 1305  (NTP V3) -');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 5905 (NTP v4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC RFC 5905 (NTP V4)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'Data Elements and Vocabularies applicable to the Common Clinical Data Set (CCDS)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'CCDS');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'Common MU Data Set: 170.207(a)(3)' and ts.deleted = false) where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'Common MU Data Set: 170.207(a)(3' and ts.deleted = false);
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'Annex A of the FIPS Publication 140-2') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'FIPS PUB 140-2 Annex A');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'Global Medical Device Nomenclature (GMDN)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'GMDN');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(f)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number like '_ 170.207(f)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(g)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number like '_ 170.207(g)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e)(1)' and ts.deleted = false) where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number like '_170.210(e)(1)' and ts.deleted = false);
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(e)(1); 170.210(e)(3); 170.210(g); 170.210(h)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number like '_170.210(e)(1); _170.210(e)(2);_170.210(e)(3); _170.210(g);_170.210(h)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g)' and ts.deleted = false and ts.certification_edition_id = 3) where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number like '_170.210(g)' and ts.deleted = false);
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(h)' and ts.deleted = false and ts.certification_edition_id = 3) where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number like '_170.210(h)' and ts.deleted = false);
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.207(f)(2) CDC Race and Ethnicity') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'Race and Ethnicity. The Office of Management and Budget Standards for Maintaining, Collecting, and Presenting Federal Data on Race and Ethnicity, Statistical Policy Directive No. 15, as revised, October 30, 1997');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 5905 (NTP v4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'RFC 5905 (NTP V4)');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 5905 (NTP v4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'RFC 5905 [NTPv4]');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 5905 (NTP v4)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'RFC 5905 NTPv4');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = '170.210(g) RFC 1305 (NTP v3)') where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'RFC1305 NTPv3');
update openchpl.certification_result_test_standard as crts set test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'SHA-384' and ts.deleted = false) where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard as ts where ts.number = 'SHA3-384');

\! echo "Deleting old ones"
update openchpl.test_standard as ts set deleted = true where ts.number = '(a)(13)(i) 170.204(b)(4)';
update openchpl.test_standard as ts set deleted = true where ts.number = '(b)(1)(iii)(B): 170.207(a)(4);CCDS: 170.207(a)(4)';
update openchpl.test_standard as ts set deleted = true where ts.number like '(b)(1)(iii)(B):170.207(a)(4);  "Assessment Section (V2)_ and _Plan of Treatment Section (V2)_ of the standard specified in _ 170.205(a)(4).';
update openchpl.test_standard as ts set deleted = true where ts.number = '(b)(1)(iii)(B):170.207(a)(4);CCDS: 170.207(a)(4)';
update openchpl.test_standard as ts set deleted = true where ts.number = '(b)(6)(ii)(B): 170.207(a)(4);CCDS: 170.207(a)(4)';
update openchpl.test_standard as ts set deleted = true where ts.number LIKE '(e) Record actions related to electronic health information, audit log status, and encryption of end-user devices._(1)(i) The audit log must record the information specified in sections 7.2 through 7.4, 7.6, and 7.7 of the standard specified at _ 170.210(h) when EHR technology is in use._(ii) The date and time must be recorded in accordance with the standard specified at _ 170.210(g)._(2)(i) The audit log must record the information specified in sections 7.2 and 7.4 of the standard specified at _ 170.210(h) when the audit log status is changed._(ii) The date and time each action occurs in accordance with the standard specified at _ 170.210(g)._(3)The audit log must record the information specified in sections 7.2 and 7.4 of the standard specified at _ 170.210(h) when the encryption status of electronic health information locally stored by EHR technology on end-user devices is changed. The date and time each action occurs in accordance with the standard specified at _ 170.210(g)._170.210(g) Synchronized clocks. The date and time recorded utilize a system clock that has been synchronized following (RFC 1305) Network Time Protocol, (incorporated by reference in _ 170.299) or (RFC 5905) Network Time Protocol Version 4, (incorporated by reference in _ 170.299)._170.210(h) Audit log content. ASTM E2147-01 (Reapproved 2009), (incorporated by reference in _ 170.299)';
update openchpl.test_standard as ts set deleted = true where ts.number LIKE '(e)(1) Record actions related to electronic health information, audit log status, and encryption of end-user devices. (i) The audit log must record the information specified in sections 7.2 through 7.4, 7.6, and 7.7 of the standard specified at _170.210(h) when EHR technology is in use._(ii) The date and time must be recorded in accordance with the standard specified at _170.210(g)._(e)(2) (i) The audit log must record the information specified in sections 7.2 and 7.4 of the standard specified at _170.210(h) when the audit log status is changed. (ii) The date and time each action occurs in accordance with the standard specified at _170.210(g)._(e)(3)The audit log must record the information specified in sections 7.2 and 7.4 of the standard specified at _170.210(h) when the encryption status of electronic health information locally stored by EHR technology on end-user devices is changed. The date and time each action occurs in accordance with the standard specified at _170.210(g)._170.210(g) Synchronized clocks. The date and time recorded utilize a system clock that has been synchronized following (RFC 1305) Network Time Protocol, (incorporated by reference in _170.299) or (RFC 5905) Network Time Protocol Version 4, (incorporated by reference in _170.299)._170.210(h) Audit log content. ASTM E2147-01 (Reapproved 2009), (incorporated by reference in _170.299)"';
update openchpl.test_standard as ts set deleted = true where ts.number = '(e)(1)(i): 170.204(a)(1);CCDS: 170.207(a)(4)';
update openchpl.test_standard as ts set deleted = true where ts.number = '(e)(1)(i): 170.204(a)(1);Optional CCDS: 170.207(a)(4);';
update openchpl.test_standard as ts set deleted = true where ts.number = '(e)(1)(ii)(A)(2): 170.210(g)  NTPv4';
update openchpl.test_standard as ts set deleted = true where ts.number = '(GMDN)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.202 (e)(1); 170.202 (a)(2)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.205(a)(4';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.205(b)(2), 170.207(d)(3)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.205(h)2; 170.205(k)1;170.205(k)2';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.205(i)(2);170.207(a)(4);170.207(c)(3)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.205(k)(1); 170.205(k)(2); 170.205(h)(2)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.205(o)(1); 170.205(a)(4)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.207(a)(4);  Assessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.207(a)(4); ssessment Section (V2) and Plan of Treatment Section (V2) of the standard specified in 170.205(a)(4)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.207(a)4';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.207(b)(2) Assessment and Plan Section (V2) of the standard specified in 170.205(a)(4)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.207(f)(2)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.207(f)(2) CDC Rance and Ethnicity Version 1.0 (September 2016)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.207(f)2; 170.207(f)1; 170.207(g)2; 170.207(n)1; 170.207(o)1';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(a)(2';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(e)(1)(2)(3); 170.210(g); 170.210(h)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(e)(1); 170.210(e)(2);70.210(e)(3):70.210(g);';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(e)(1);(2);(3); 170.201(g);(h)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(e);170.210(g) ; 170.210(h)';
update openchpl.test_standard as ts set deleted = true where ts.number like '170.210(f)_';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(g) NTP v3';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(g) NTP v4';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(g) NTPv3';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(g) NTPv4';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(g) RFC 1305  (NTP V3)';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(g) RFC 1305  (NTP V3) -';
update openchpl.test_standard as ts set deleted = true where ts.number = '170.210(g) RFC RFC 5905 (NTP V4)';
update openchpl.test_standard as ts set deleted = true where ts.number = 'CCDS';
update openchpl.test_standard as ts set deleted = true where ts.number = 'Common MU Data Set: 170.207(a)(3' and ts.deleted = false;
update openchpl.test_standard as ts set deleted = true where ts.number = 'FIPS PUB 140-2 Annex A';
update openchpl.test_standard as ts set deleted = true where ts.number = 'GMDN';
update openchpl.test_standard as ts set deleted = true where ts.number like '_ 170.207(f)';
update openchpl.test_standard as ts set deleted = true where ts.number like '_ 170.207(g)';
update openchpl.test_standard as ts set deleted = true where ts.number like '_170.210(e)(1)' and ts.deleted = false;
update openchpl.test_standard as ts set deleted = true where ts.number like '_170.210(e)(1); _170.210(e)(2);_170.210(e)(3); _170.210(g);_170.210(h)';
update openchpl.test_standard as ts set deleted = true where ts.number like '_170.210(g)' and ts.deleted = false;
update openchpl.test_standard as ts set deleted = true where ts.number like '_170.210(h)' and ts.deleted = false;
update openchpl.test_standard as ts set deleted = true where ts.number = 'Race and Ethnicity. The Office of Management and Budget Standards for Maintaining, Collecting, and Presenting Federal Data on Race and Ethnicity, Statistical Policy Directive No. 15, as revised, October 30, 1997';
update openchpl.test_standard as ts set deleted = true where ts.number = 'RFC 5905 (NTP V4)';
update openchpl.test_standard as ts set deleted = true where ts.number = 'RFC 5905 [NTPv4]';
update openchpl.test_standard as ts set deleted = true where ts.number = 'RFC 5905 NTPv4';
update openchpl.test_standard as ts set deleted = true where ts.number = 'RFC1305 NTPv3';
update openchpl.test_standard as ts set deleted = true where ts.number = 'SHA3-384';

\! echo "Adding multi-row"
insert into openchpl.certification_result_test_standard (certification_result_id, test_standard_id, last_modified_user, deleted)
    values ((select crts.certification_result_id from openchpl.certification_result_test_standard crts where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard ts where ts.number like 'Annex A of the FIPS Publication 140-2_(e)(1)(ii)(A)(2): 170.210(g) NTP v3 _Common MU Data Set: 170.207(a)(3)')),
        (select ts.test_standard_id from openchpl.test_standard ts where ts.number = 'Annex A of the FIPS Publication 140-2' and ts.deleted = false),
        -1, false),
    ((select crts.certification_result_id from openchpl.certification_result_test_standard crts where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard ts where ts.number like 'Annex A of the FIPS Publication 140-2_(e)(1)(ii)(A)(2): 170.210(g) NTP v3 _Common MU Data Set: 170.207(a)(3)')),
        (select ts.test_standard_id from openchpl.test_standard ts where ts.number = 'Common MU Data Set: 170.207(a)(3)' and ts.deleted = false),
        -1, false),
    ((select crts.certification_result_id from openchpl.certification_result_test_standard crts where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard ts where ts.number like 'Annex A of the FIPS Publication 140-2_(e)(1)(ii)(A)(2): 170.210(g) NTP v3 OR 170.210(g) NTPv4_Common MU Data Set: 170.207(a)(3), 170.207(b)(2) or 170.207 (b)(3)')),
        (select ts.test_standard_id from openchpl.test_standard ts where ts.number = 'Annex A of the FIPS Publication 140-2' and ts.deleted = false),
        -1, false),
    ((select crts.certification_result_id from openchpl.certification_result_test_standard crts where crts.test_standard_id = (select ts.test_standard_id from openchpl.test_standard ts where ts.number like 'Annex A of the FIPS Publication 140-2_(e)(1)(ii)(A)(2): 170.210(g) NTP v3 OR 170.210(g) NTPv4_Common MU Data Set: 170.207(a)(3), 170.207(b)(2) or 170.207 (b)(3)')),
        (select ts.test_standard_id from openchpl.test_standard ts where ts.number = 'Common MU Data Set: 170.207(a)(3), 170.207(b)(2) or 170.207 (b)(3)' and ts.deleted = false),
        -1, false);

update openchpl.test_standard ts set number = '(e)(1)(ii)(A)(2): 170.210(g) NTP v3 OR 170.210(g) NTPv4' where ts.number like 'Annex A of the FIPS Publication 140-2_(e)(1)(ii)(A)(2): 170.210(g) NTP v3 OR 170.210(g) NTPv4_Common MU Data Set: 170.207(a)(3), 170.207(b)(2) or 170.207 (b)(3)';
update openchpl.test_standard ts set number = '(e)(1)(ii)(A)(2): 170.210(g) NTP v3' where ts.number like 'Annex A of the FIPS Publication 140-2_(e)(1)(ii)(A)(2): 170.210(g) NTP v3 _Common MU Data Set: 170.207(a)(3)';
