--
-- Add new job type for surveillance upload
--
INSERT INTO openchpl.job_type (name, description, success_message, last_modified_user, deleted)
SELECT 'Surveillance Upload', 'Uploading a file with many surveillance items.', 'Surveillance upload is complete', -1, FALSE
WHERE NOT EXISTS (
	SELECT * FROM openchpl.job_type WHERE name = 'Surveillance Upload'
);


--
-- OCD-1964
--
CREATE OR REPLACE VIEW openchpl.developer_certification_statuses AS
SELECT v.vendor_id,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Active'::text) AS active,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Retired'::text) AS retired,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Withdrawn by Developer'::text) AS withdrawn_by_developer,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Withdrawn by ONC-ACB'::text) AS withdrawn_by_acb,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Suspended by ONC-ACB'::text) AS suspended_by_acb,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Suspended by ONC'::text) AS suspended_by_onc,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Terminated by ONC'::text) AS terminated_by_onc
FROM openchpl.vendor v
    LEFT JOIN openchpl.product p ON v.vendor_id = p.vendor_id
    LEFT JOIN openchpl.product_version pv ON p.product_id = pv.product_id
    LEFT JOIN openchpl.certified_product cp ON pv.product_version_id = cp.product_version_id
	--certification status
	LEFT JOIN (
		SELECT cse.certification_status_id as "certification_status_id", cse.certified_product_id as "certified_product_id"
		FROM openchpl.certification_status_event cse
		INNER JOIN
			(SELECT certified_product_id, extract(epoch from MAX(event_date)) event_date
			FROM openchpl.certification_status_event
			GROUP BY certified_product_id) maxCse
		ON cse.certified_product_id = maxCse.certified_product_id
		--conversion to epoch/long comparison significantly faster than comparing the timestamp fields as-is
		AND extract(epoch from cse.event_date) = maxCse.event_date
	) lastCertStatusEvent
	ON lastCertStatusEvent.certified_product_id = cp.certified_product_id

    LEFT JOIN openchpl.certification_status cs ON lastCertStatusEvent.certification_status_id = cs.certification_status_id
GROUP BY v.vendor_id;

CREATE OR REPLACE VIEW openchpl.product_certification_statuses AS
SELECT p.product_id,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Active'::text) AS active,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Retired'::text) AS retired,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Withdrawn by Developer'::text) AS withdrawn_by_developer,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Withdrawn by ONC-ACB'::text) AS withdrawn_by_acb,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Suspended by ONC-ACB'::text) AS suspended_by_acb,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Suspended by ONC'::text) AS suspended_by_onc,
    count(cp.certified_product_id) FILTER (WHERE cs.certification_status::text = 'Terminated by ONC'::text) AS terminated_by_onc
FROM openchpl.product p
    LEFT JOIN openchpl.product_version pv ON p.product_id = pv.product_id
    LEFT JOIN openchpl.certified_product cp ON pv.product_version_id = cp.product_version_id
    --certification status
	LEFT JOIN (
		SELECT cse.certification_status_id as "certification_status_id", cse.certified_product_id as "certified_product_id"
		FROM openchpl.certification_status_event cse
		INNER JOIN
			(SELECT certified_product_id, extract(epoch from MAX(event_date)) event_date
			FROM openchpl.certification_status_event
			GROUP BY certified_product_id) maxCse
		ON cse.certified_product_id = maxCse.certified_product_id
		--conversion to epoch/long comparison significantly faster than comparing the timestamp fields as-is
		AND extract(epoch from cse.event_date) = maxCse.event_date
	) lastCertStatusEvent
	ON lastCertStatusEvent.certified_product_id = cp.certified_product_id

    LEFT JOIN openchpl.certification_status cs ON lastCertStatusEvent.certification_status_id = cs.certification_status_id
GROUP BY p.product_id;

-- the above views referenced this column; replace it first
ALTER TABLE openchpl.certified_product DROP COLUMN IF EXISTS certification_status_id;

ALTER TABLE openchpl.certification_status_event DROP COLUMN IF EXISTS reason;
ALTER TABLE openchpl.certification_status_event ADD COLUMN reason varchar(500);

ALTER TABLE openchpl.pending_certified_product
DROP COLUMN IF EXISTS has_qms;

ALTER TABLE openchpl.pending_certified_product
ADD COLUMN has_qms boolean;

-- OCD-1988: deprecate 2015 v11 template
update openchpl.upload_template_version set deprecated = true where "name"='2015 CHPL Upload Template v11';

-- ocd-1983
insert into openchpl.cqm_version (version, last_modified_user) select 'v7', -1
WHERE NOT EXISTS (
	SELECT * FROM openchpl.cqm_version WHERE version = 'v7'
);

INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS2', 8, 'Preventive Care and Screening: Screening for Depression and Follow-Up Plan', '418', null, 'Percentage of patients aged 12 years and older screened for depression on the date of the encounter using an age appropriate standardized depression screening tool AND if positive, a follow-up plan is documented on the date of the positive screen', 'Community/Population Health', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS2' and cqm_version_id = 8);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS9', 7, 'Exclusive Breast Milk Feeding', '480', null, 'Exclusive breast milk feeding during the newborn''s entire hospitalization', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS9' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS22', 7, 'Preventive Care and Screening: Screening for High Blood Pressure and Follow-Up Documented', 'N/A', null, 'Percentage of patients aged 18 years and older seen during the reporting period who were screened for high blood pressure AND a recommended follow-up plan is documented based on the current blood pressure (BP) reading as indicated', 'Community/Population Health', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS22' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS26', 6, 'Home Management Plan of Care (HMPC) Document Given to Patient/Caregiver', 'N/A', null, 'An assessment that there is documentation in the medical record that a Home Management Plan of Care (HMPC) document was given to the pediatric asthma patient/caregiver', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS26' and cqm_version_id = 6);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS31', 7, 'Hearing Screening Prior To Hospital Discharge', '1354', null, 'This measure assesses the proportion of births that have been screened for hearing loss before hospital discharge', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS31' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS32', 8, 'Median Time from ED Arrival to ED Departure for Discharged ED Patients', '496', null, 'Median elapsed time from emergency department arrival to emergency room departure for patients discharged from the emergency department', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS32' and cqm_version_id = 8);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS50', 7, 'Closing the Referral Loop: Receipt of Specialist Report', 'N/A', null, 'Percentage of patients with referrals, regardless of age, for which the referring provider receives a report from the provider to whom the patient was referred', 'Communication and Care Coordination', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS50' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS52', 7, 'HIV/AIDS: Pneumocystis Jiroveci Pneumonia (PCP) Prophylaxis', '405', null, 'Percentage of patients aged 6 weeks and older with a diagnosis of HIV/AIDS who were prescribed Pneumocystis jiroveci pneumonia (PCP) prophylaxis', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS52' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS53', 7, 'Primary PCI Received Within 90 Minutes of Hospital Arrival', 'N/A', null, 'Acute myocardial infarction (AMI) patients with ST-segment elevation on the ECG closest to arrival time receiving primary PCI during the hospital stay with a time from hospital arrival to PCI of 90 minutes or less', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS53' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS55', 7, 'Median Time from ED Arrival to ED Departure for Admitted ED Patients', '495', null, 'Median time from emergency department arrival to time of departure from the emergency room for patients admitted to the facility from the emergency department', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS55' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS56', 7, 'Functional Status Assessment for Total Hip Replacement', 'N/A', null, 'Percentage of patients 18 years of age and older who received an elective primary total hip arthroplasty (THA) and completed a functional status assessment within 90 days prior to the surgery and in the 270-365 days after the surgery', 'Person and Caregiver-Centered Experience and Outcome', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS56' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS65', 8, 'Hypertension: Improvement in Blood Pressure', 'N/A', null, 'Percentage of patients aged 18-85 years of age with a diagnosis of hypertension whose blood pressure improved during the measurement period', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS65' and cqm_version_id = 8);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS66', 7, 'Functional Status Assessment for Total Knee Replacement', 'N/A', null, 'Percentage of patients 18 years of age and older who received an elective primary total knee arthroplasty (TKA) and completed a functional status assessment within 90 days prior to the surgery and in the 270-365 days after the surgery', 'Person and Caregiver-Centered Experience and Outcome', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS66' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS68', 8, 'Documentation of Current Medications in the Medical Record', '419', null, 'Percentage of visits for patients aged 18 years and older for which the eligible professional or eligible clinician attests to documenting a list of current medications using all immediate resources available on the date of the encounter. This list must include ALL known prescriptions, over-the-counters, herbals, and vitamin/mineral/dietary (nutritional) supplements AND must contain the medications'' name, dosage, frequency and route of administration.', 'Patient Safety', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS68' and cqm_version_id = 8);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS69', 7, 'Preventive Care and Screening: Body Mass Index (BMI) Screening and Follow-Up Plan', '421', null, 'Percentage of patients aged 18 years and older with a BMI documented during the current encounter or during the previous twelve months AND with a BMI outside of normal parameters, a follow-up plan is documented during the encounter or during the previous twelve months of the current encounter. Normal Parameters: Age 18 years and older BMI => 18.5 and < 25 kg/m2', 'Community/Population Health', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS69' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS71', 8, 'Anticoagulation Therapy for Atrial Fibrillation/Flutter', 'N/A', null, 'Ischemic stroke patients with atrial fibrillation/flutter who are prescribed or continuing to take anticoagulation therapy at hospital discharge', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS71' and cqm_version_id = 8);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS72', 7, 'Antithrombotic Therapy By End of Hospital Day 2', 'N/A', null, 'Ischemic stroke patients administered antithrombotic therapy by the end of hospital day 2', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS72' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS74', 8, 'Primary Caries Prevention Intervention as Offered by Primary Care Providers, including Dentists', 'N/A', null, 'Percentage of children, age 0-20 years, who received a fluoride varnish application during the measurement period', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS74' and cqm_version_id = 8);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS75', 7, 'Children Who Have Dental Decay or Cavities', 'N/A', null, 'Percentage of children, age 0-20 years, who have had tooth decay or cavities during the measurement period', 'Community/Population Health', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS75' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS82', 6, 'Maternal Depression Screening', 'N/A', null, 'The percentage of children who turned 6 months of age during the measurement year, who had a face-to-face visit between the clinician and the child during child''s first 6 months, and who had a maternal depression screening for the mother at least once between 0 and 6 months of life', 'Community/Population Health', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS82' and cqm_version_id = 6);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS90', 8, 'Functional Status Assessments for Congestive Heart Failure', 'N/A', null, 'Percentage of patients 18 years of age and older with congestive heart failure who completed initial and follow-up patient-reported functional status assessments', 'Person and Caregiver-Centered Experience and Outcome', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS90' and cqm_version_id = 8);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS102', 7, 'Assessed for Rehabilitation', 'N/A', null, 'Ischemic or hemorrhagic stroke patients who were assessed for rehabilitation services', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS102' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS104', 7, 'Discharged on Antithrombotic Therapy', 'N/A', null, 'Ischemic stroke patients prescribed or continuing to take antithrombotic therapy at hospital discharge', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS104' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS105', 7, 'Discharged on Statin Medication', 'N/A', null, 'Ischemic stroke patients who are prescribed or continuing to take statin medication at hospital discharge', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS105' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS107', 7, 'Stroke Education', 'N/A', null, 'Ischemic or hemorrhagic stroke patients or their caregivers who were given educational materials during the hospital stay addressing all of the following: activation of emergency medical system, need for follow-up after discharge, medications prescribed at discharge, risk factors for stroke, and warning signs and symptoms of stroke', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS107' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS108', 7, 'Venous Thromboembolism Prophylaxis', '371', null, 'This measure assesses the number of patients who received VTE prophylaxis or have documentation why no VTE prophylaxis was given the day of or the day after hospital admission or surgery end date for surgeries that start the day of or the day after hospital admission', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS108' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS111', 7, 'Median Admit Decision Time to ED Departure Time for Admitted Patients', '497', null, 'Median time (in minutes) from admit decision time to time of departure from the emergency department for emergency department patients admitted to inpatient status.', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS111' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS113', 7, 'Elective Delivery', '469', null, 'Patients with elective vaginal deliveries or elective cesarean births at >= 37 and < 39 weeks of gestation completed', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS113' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS117', 7, 'Childhood Immunization Status', '38', null, 'Percentage of children 2 years of age who had four diphtheria, tetanus and acellular pertussis (DTaP); three polio (IPV), one measles, mumps and rubella (MMR); three H influenza type B (HiB); three hepatitis B (Hep B); one chicken pox (VZV); four pneumococcal conjugate (PCV); one hepatitis A (Hep A); two or three rotavirus (RV); and two influenza (flu) vaccines by their second birthday', 'Community/Population Health', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS117' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS122', 7, 'Diabetes: Hemoglobin A1c (HbA1c) Poor Control (> 9%)', '59', null, 'Percentage of patients 18-75 years of age with diabetes who had hemoglobin A1c > 9.0% during the measurement period', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS122' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS123', 7, 'Diabetes: Foot Exam', '56', null, 'The percentage of patients 18-75 years of age with diabetes (type 1 and type 2) who received a foot exam (visual inspection and sensory exam with mono filament and a pulse exam) during the measurement year', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS123' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS124', 7, 'Cervical Cancer Screening', '32', null, 'Percentage of women 21-64 years of age who were screened for cervical cancer using either of the following criteria: Women age 21-64 who had cervical cytology performed every 3 years; Women age 30-64 who had cervical cytology/human papillomavirus (HPV) co-testing performed every 5 years', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS124' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS125', 7, 'Breast Cancer Screening', '2372', null, 'Percentage of women 50-74 years of age who had a mammogram to screen for breast cancer', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS125' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS127', 7, 'Pneumococcal Vaccination Status for Older Adults', 'N/A', null, 'Percentage of patients 65 years of age and older who have ever received a pneumococcal vaccine', 'Community/Population Health', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS127' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS128', 7, 'Anti-depressant Medication Management', '105', null, 'Percentage of patients 18 years of age and older who were treated with antidepressant medication, had a diagnosis of major depression, and who remained on an antidepressant medication treatment. Two rates are reported: a. Percentage of patients who remained on an antidepressant medication for at least 84 days (12 weeks).; b. Percentage of patients who remained on an antidepressant medication for at least 180 days (6 months).', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS128' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS129', 8, 'Prostate Cancer: Avoidance of Overuse of Bone Scan for Staging Low Risk Prostate Cancer Patients', '389', null, 'Percentage of patients, regardless of age, with a diagnosis of prostate cancer at low (or very low) risk of recurrence receiving interstitial prostate brachytherapy, OR external beam radiotherapy to the prostate, OR radical prostatectomy, OR cryotherapy who did not have a bone scan performed at any time since diagnosis of prostate cancer', 'Efficiency and Cost Reduction', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS129' and cqm_version_id = 8);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS130', 7, 'Colorectal Cancer Screening', '34', null, 'Percentage of adults 50-75 years of age who had appropriate screening for colorectal cancer', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS130' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS131', 7, 'Diabetes: Eye Exam', '55', null, 'Percentage of patients 18-75 years of age with diabetes who had a retinal or dilated eye exam by an eye care professional during the measurement period or a negative retinal exam (no evidence of retinopathy) in the 12 months prior to the measurement period', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS131' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS132', 7, 'Cataracts: Complications within 30 Days Following Cataract Surgery Requiring Additional Surgical Procedures', '564', null, 'Percentage of patients aged 18 years and older with a diagnosis of uncomplicated cataract who had cataract surgery and had any of a specified list of surgical procedures in the 30 days following cataract surgery which would indicate the occurrence of any of the following major complications: retained nuclear fragments, endophthalmitis, dislocated or wrong power IOL, retinal detachment, or wound dehiscence', 'Patient Safety', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS132' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS133', 7, 'Cataracts: 20/40 or Better Visual Acuity within 90 Days Following Cataract Surgery', '565', null, 'Percentage of patients aged 18 years and older with a diagnosis of uncomplicated cataract who had cataract surgery and no significant ocular conditions impacting the visual outcome of surgery and had best-corrected visual acuity of 20/40 or better (distance or near) achieved within 90 days following the cataract surgery', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS133' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS134', 7, 'Diabetes: Medical Attention for Nephropathy', '62', null, 'The percentage of patients 18-75 years of age with diabetes who had a nephropathy screening test or evidence of nephropathy during the measurement period', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS134' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS135', 7, 'Heart Failure (HF): Angiotensin-Converting Enzyme (ACE) Inhibitor or Angiotensin Receptor Blocker (ARB) Therapy for Left Ventricular Systolic Dysfunction (LVSD)', '81', null, 'Percentage of patients aged 18 years and older with a diagnosis of heart failure (HF) with a current or prior left ventricular ejection fraction (LVEF) < 40% who were prescribed ACE inhibitor or ARB therapy either within a 12 month period when seen in the outpatient setting OR at each hospital discharge', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS135' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS136', 8, 'Follow-Up Care for Children Prescribed ADHD Medication (ADD)', '108', null, 'Percentage of children 6-12 years of age and newly dispensed a medication for attention-deficit/hyperactivity disorder (ADHD) who had appropriate follow-up care. Two rates are reported: a. Percentage of children who had one follow-up visit with a practitioner with prescribing authority during the 30-Day Initiation Phase.; b. Percentage of children who remained on ADHD medication for at least 210 days and who, in addition to the visit in the Initiation Phase, had at least two additional follow-up visits with a practitioner within 270 days (9 months) after the Initiation Phase ended.', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS136' and cqm_version_id = 8);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS137', 7, 'Initiation and Engagement of Alcohol and Other Drug Dependence Treatment', '4', null, 'Percentage of patients 13 years of age and older with a new episode of alcohol and other drug (AOD) dependence who received the following. Two rates are reported: a. Percentage of patients who initiated treatment within 14 days of the diagnosis.; b. Percentage of patients who initiated treatment and who had two or more additional services with an AOD diagnosis within 30 days of the initiation visit.', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS137' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS138', 7, 'Preventive Care and Screening: Tobacco Use: Screening and Cessation Intervention', '28', null, 'Percentage of patients aged 18 years and older who were screened for tobacco use one or more times within 24 months AND who received tobacco cessation intervention if identified as a tobacco user. Three rates are reported: a. Percentage of patients aged 18 years and older who were screened for tobacco use one or more times within 24 months; b. Percentage of patients aged 18 years and older who were screened for tobacco use and identified as a tobacco user who received tobacco cessation intervention; c. Percentage of patients aged 18 years and older who were screened for tobacco use one or more times within 24 months AND who received tobacco cessation intervention if identified as a tobacco user', 'Community/Population Health', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS138' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS139', 7, 'Falls: Screening for Future Fall Risk', '101', null, 'Percentage of patients 65 years of age and older who were screened for future fall risk during the measurement period', 'Patient Safety', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS139' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS142', 7, 'Diabetic Retinopathy: Communication with the Physician Managing Ongoing Diabetes Care', '89', null, 'Percentage of patients aged 18 years and older with a diagnosis of diabetic retinopathy who had a dilated macular or fundus exam performed with documented communication to the physician who manages the ongoing care of the patient with diabetes mellitus regarding the findings of the macular or fundus exam at least once within 12 months', 'Communication and Care Coordination', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS142' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS143', 7, 'Primary Open-Angle Glaucoma (POAG): Optic Nerve Evaluation', '86', null, 'Percentage of patients aged 18 years and older with a diagnosis of primary open-angle glaucoma (POAG) who have an optic nerve head evaluation during one or more office visits within 12 months', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS143' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS144', 7, 'Heart Failure (HF): Beta-Blocker Therapy for Left Ventricular Systolic Dysfunction (LVSD)', '83', null, 'Percentage of patients aged 18 years and older with a diagnosis of heart failure (HF) with a current or prior left ventricular ejection fraction (LVEF) < 40% who were prescribed beta-blocker therapy either within a 12 month period when seen in the outpatient setting OR at each hospital discharge', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS144' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS145', 7, 'Coronary Artery Disease (CAD): Beta-Blocker Therapy-Prior Myocardial Infarction (MI) or Left Ventricular Systolic Dysfunction (LVEF <40%)', '70', null, 'Percentage of patients aged 18 years and older with a diagnosis of coronary artery disease seen within a 12 month period who also have a prior MI or a current or prior LVEF <40% who were prescribed beta-blocker therapy', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS145' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS146', 7, 'Appropriate Testing for Children with Pharyngitis', 'N/A', null, 'Percentage of children 3-18 years of age who were diagnosed with pharyngitis, ordered an antibiotic and received a group A streptococcus (strep) test for the episode', 'Efficiency and Cost Reduction', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS146' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS147', 8, 'Preventive Care and Screening: Influenza Immunization', '41', null, 'Percentage of patients aged 6 months and older seen for a visit between October 1 and March 31 who received an influenza immunization OR who reported previous receipt of an influenza immunization', 'Community/Population Health', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS147' and cqm_version_id = 8);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS149', 7, 'Dementia: Cognitive Assessment', '2872', null, 'Percentage of patients, regardless of age, with a diagnosis of dementia for whom an assessment of cognition is performed and the results reviewed at least once within a 12 month period', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS149' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS153', 7, 'Chlamydia Screening for Women', '33', null, 'Percentage of women 16-24 years of age who were identified as sexually active and who had at least one test for chlamydia during the measurement period', 'Community/Population Health', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS153' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS154', 7, 'Appropriate Treatment for Children with Upper Respiratory Infection (URI)', '69', null, 'Percentage of children 3 months-18 years of age who were diagnosed with upper respiratory infection (URI) and were not dispensed an antibiotic prescription on or three days after the episode', 'Efficiency and Cost Reduction', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS154' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS155', 7, 'Weight Assessment and Counseling for Nutrition and Physical Activity for Children and Adolescents', '24', null, 'Percentage of patients 3-17 years of age who had an outpatient visit with a Primary Care Physician (PCP) or Obstetrician/Gynecologist (OB/GYN) and who had evidence of the following during the measurement period. Three rates are reported: Percentage of patients with height, weight, and body mass index (BMI) percentile documentation; Percentage of patients with counseling for nutrition; Percentage of patients with counseling for physical activity', 'Community/Population Health', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS155' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS156', 7, 'Use of High-Risk Medications in the Elderly', '22', null, 'Percentage of patients 65 years of age and older who were ordered high-risk medications. Two rates are reported: a. Percentage of patients who were ordered at least one high-risk medication.; b. Percentage of patients who were ordered at least two of the same high-risk medications.', 'Patient Safety', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS156' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS157', 7, 'Oncology: Medical and Radiation - Pain Intensity Quantified', '384', null, 'Percentage of patient visits, regardless of patient age, with a diagnosis of cancer currently receiving chemotherapy or radiation therapy in which pain intensity is quantified', 'Person and Caregiver-Centered Experience and Outcome', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS157' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS158', 7, 'Pregnant women that had HBsAg testing', 'N/A', null, 'This measure identifies pregnant women who had a HBsAg (hepatitis B) test during their pregnancy', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS158' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS159', 7, 'Depression Remission at Twelve Months', '710', null, 'The percentage of patients 18 years of age or older with major depression or dysthymia who reached remission 12 months (+/- 30 days) after an index visit.', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS159' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS160', 7, 'Depression Utilization of the PHQ-9 Tool', '712', null, 'The percentage of patients age 18 and older with the diagnosis of major depression or dysthymia who have a completed PHQ-9 during each applicable 4 month period in which there was a qualifying visit', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS160' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS161', 7, 'Adult Major Depressive Disorder (MDD): Suicide Risk Assessment', '104', null, 'Percentage of patients aged 18 years and older with a diagnosis of major depressive disorder (MDD) with a suicide risk assessment completed during the visit in which a new diagnosis or recurrent episode was identified', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS161' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS164', 7, 'Ischemic Vascular Disease (IVD): Use of Aspirin or Another Antiplatelet', '68', null, 'Percentage of patients 18 years of age and older who were diagnosed with acute myocardial infarction (AMI), coronary artery bypass graft (CABG) or percutaneous coronary interventions (PCI) in the 12 months prior to the measurement period, or who had an active diagnosis of ischemic vascular disease (IVD) during the measurement period, and who had documentation of use of aspirin or another antiplatelet during the measurement period', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS164' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS165', 7, 'Controlling High Blood Pressure', '18', null, 'Percentage of patients 18-85 years of age who had a diagnosis of hypertension and whose blood pressure was adequately controlled (<140/90mmHg) during the measurement period', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS165' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS166', 8, 'Use of Imaging Studies for Low Back Pain', '52', null, 'Percentage of patients 18-50 years of age with a diagnosis of low back pain who did not have an imaging study (plain X-ray, MRI, CT scan) within 28 days of the diagnosis', 'Efficiency and Cost Reduction', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS166' and cqm_version_id = 8);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS167', 7, 'Diabetic Retinopathy: Documentation of Presence or Absence of Macular Edema and Level of Severity of Retinopathy', '88', null, 'Percentage of patients aged 18 years and older with a diagnosis of diabetic retinopathy who had a dilated macular or fundus exam performed which included documentation of the level of severity of retinopathy and the presence or absence of macular edema during one or more office visits within 12 months', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS167' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS169', 7, 'Bipolar Disorder and Major Depression: Appraisal for alcohol or chemical substance use', 'N/A', null, 'Percentage of patients with depression or bipolar disorder with evidence of an initial assessment that includes an appraisal for alcohol or chemical substance use', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS169' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS177', 7, 'Child and Adolescent Major Depressive Disorder (MDD): Suicide Risk Assessment', '1365', null, 'Percentage of patient visits for those patients aged 6 through 17 years with a diagnosis of major depressive disorder with an assessment for suicide risk', 'Patient Safety', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS177' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS190', 7, 'Intensive Care Unit Venous Thromboembolism Prophylaxis', '372', null, 'This measure assesses the number of patients who received VTE prophylaxis or have documentation why no VTE prophylaxis was given the day of or the day after the initial admission (or transfer) to the Intensive Care Unit (ICU) or surgery end date for surgeries that start the day of or the day after ICU admission (or transfer)', '', 2, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS190' and cqm_version_id = 7);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS347', 2, 'Statin Therapy for the Prevention and Treatment of Cardiovascular Disease', 'N/A', null, 'Percentage of the following patients - all considered at high risk of cardiovascular events - who were prescribed or were on statin therapy during the measurement period: Adults aged >= 21 years who were previously diagnosed with or currently have an active diagnosis of clinical atherosclerotic cardiovascular disease (ASCVD); OR Adults aged >= 21 years who have ever had a fasting or direct low-density lipoprotein cholesterol (LDL-C) level >= 190 mg/dL or were previously diagnosed with or currently have an active diagnosis of familial or pure hypercholesterolemia; OR Adults aged 40-75 years with a diagnosis of diabetes with a fasting or direct LDL-C level of 70-189 mg/dL', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS347' and cqm_version_id = 2);
INSERT INTO openchpl.cqm_criterion (cms_id, cqm_version_id, title, nqf_number, number, description, cqm_domain, cqm_criterion_type_id, last_modified_user, retired) SELECT 'CMS645', 2, 'Bone density evaluation for patients with prostate cancer and receiving androgen deprivation therapy', 'N/A', null, 'Patients determined as having prostate cancer who are currently starting or undergoing androgen deprivation therapy (ADT), for an anticipated period of 12 months or greater and who receive an initial bone density evaluation. The bone density evaluation must be prior to the start of ADT or within 3 months of the start of ADT.', 'Effective Clinical Care', 1, -1, false WHERE NOT EXISTS ( select * from openchpl.cqm_criterion where cms_id = 'CMS645' and cqm_version_id = 2);

--re-run grants
\i dev/openchpl_grant-all.sql
