UPDATE openchpl.test_functionality SET number = '(a)(4)(iii)' WHERE "name" = 'Optional: (a)(4)(iii) Plot and electronically display, upon request, growth charts for patients';
UPDATE openchpl.test_functionality SET number = '(b)(1)(i)(B)' WHERE "name" = 'Optional: (b)(1)(i)(B) The standards specified in § 170.202(a) and (b)';
UPDATE openchpl.test_functionality SET number = '(b)(1)(i)(C)' WHERE "name" = 'Optional: (b)(1)(i)(C) The standards specified in § 170.202(b) and (c)';
UPDATE openchpl.test_functionality SET number = '(f)(3)(i)(B)' WHERE "name" = 'Optional: (f)(3)(i)(B) The standard (and applicable implementation specifications) specified in §170.205(d)(3)';
UPDATE openchpl.test_functionality SET number = '(f)(7)(i)' WHERE "name" = 'Optional: (f)(7)(i) That contains the following data: (A) Patient demographics; (B) Provider specialty; (C) Provider address; (D) Problem list; (E) Vital signs; (F) Laboratory test values/results; (G) Procedures; (H) Medication list; and (I) Insurance';
UPDATE openchpl.test_functionality SET number = '(a)(5)(i)' WHERE "name" = 'Ambulatory setting: (a)(5)(i) Over multiple encounters in accordance with, at a minimum, the version of the standard specified in §170.207(a)(3)';
UPDATE openchpl.test_functionality SET number = '(a)(6)(i)' WHERE "name" = 'Ambulatory setting: (a)(6)(i) Over multiple encounters';
UPDATE openchpl.test_functionality SET number = '(a)(7)(i)' WHERE "name" = 'Ambulatory setting: (a)(7)(i) Over multiple encounters';
UPDATE openchpl.test_functionality SET number = '(a)(8)(iii)(B)(3)' WHERE "name" = 'Ambulatory setting: (a)(8)(iii)(B)(3) When a patient’s laboratory tests and values/results are incorporated pursuant to paragraph (b)(5)(i)(A)(1) of this section';
UPDATE openchpl.test_functionality SET number = '(a)(14)(vi)' WHERE "name" = 'Ambulatory setting: (a)(14)(vi) Patient communication preferences';
UPDATE openchpl.test_functionality SET number = '(b)(2)(i)(E)' WHERE "name" = 'Ambulatory setting: (b)(2)(i)(E) The reason for referral; and referring or transitioning provider''s name and office contact information';
UPDATE openchpl.test_functionality SET number = '(b)(7)(v)' WHERE "name" = 'Ambulatory setting: (b)(7)(v) The reason for referral; and referring or transitioning provider''s name and office contact information';
UPDATE openchpl.test_functionality SET number = '(b)(8)(iii)(E)' WHERE "name" = 'Ambulatory setting: (b)(8)(iii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(A)(2)' WHERE "name" = 'Ambulatory setting: (e)(1)(i)(A)(2) Provider''s name and office contact information';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(B)(1)(i)' WHERE "name" = 'Ambulatory setting: (e)(1)(i)(B)(1)(i) All of the data in the Common MU Data Set (which should be in their English (i.e., noncoded) representation if they associate with a vocabulary/code set) and the Provider''s name and office contact information';
UPDATE openchpl.test_functionality SET number = '(f)(3)(i)' WHERE "name" = 'Ambulatory setting: (f)(3)(i) (A) The standard specified in §170.205(d)(2). (B) Optional. The standard (and applicable implementation specifications) specified in §170.205(d)(3)';
UPDATE openchpl.test_functionality SET number = '(a)(5)(ii)' WHERE "name" = 'Inpatient setting: (a)(5)(ii) For the duration of an entire hospitalization in accordance with, at a minimum, the version of the standard specified in §170.207(a)(3)';
UPDATE openchpl.test_functionality SET number = '(a)(6)(ii)' WHERE "name" = 'Inpatient setting: (a)(6)(ii) For the duration of an entire hospitalization';
UPDATE openchpl.test_functionality SET number = '(a)(7)(ii)' WHERE "name" = 'Inpatient setting: (a)(7)(ii) For the duration of an entire hospitalization';
UPDATE openchpl.test_functionality SET number = '(b)(2)(i)(F)' WHERE "name" = 'Inpatient setting: (b)(2)(i)(F) Discharge instructions';
UPDATE openchpl.test_functionality SET number = '(b)(7)(vi)' WHERE "name" = 'Inpatient setting: (b)(7)(vi) Discharge Instructions';
UPDATE openchpl.test_functionality SET number = '(b)(8)(iii)(F)' WHERE "name" = 'Inpatient setting: (b)(8)(iii)(F) Discharge Instructions';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(A)(3)' WHERE "name" = 'Inpatient setting: (e)(1)(i)(A)(3) Admission and discharge dates and locations; discharge instructions; and reason(s) for hospitalization';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(B)(1)(ii)' WHERE "name" = 'Inpatient setting: (e)(1)(i)(B)(1)(ii) All of the data in the Common MU Data Set (which should be in their English (i.e., noncoded) representation if they associate with a vocabulary/code set) and the admission and discharge dates and locations; discharge instructions; and reason(s) for hospitalization';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(B)(2)' WHERE "name" = 'Inpatient setting: (e)(1)(i)(B)(2) Electronically download transition of care/referral summaries that were created as a result of a transition of care (pursuant to the capability expressed in the certification criterion adopted at paragraph (b)(2) of this section)';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(C)(2)' WHERE "name" = 'Inpatient setting: (e)(1)(i)(C)(2) Electronically transmit transition of care/referral summaries (as a result of a transition of care/referral) selected by the patient (or their authorized representative) in accordance with at least one of the following: (i) The standard specified in §170.202(a). (ii) Through a method that conforms to the standard specified at §170.202(d) and that leads to such summary being processed by a service that has implemented the standard specified in §170.202(a)';
UPDATE openchpl.test_functionality SET number = '(f)(3)(ii)' WHERE "name" = 'Inpatient setting: (f)(3)(ii)  The standard (and applicable implementation specifications) specified in §170.205(d)(3)';
UPDATE openchpl.test_functionality SET number = '(a)(4)(ii)(B)(1)' WHERE "name" ='Alternative: (a)(4)(ii)(B)(1) To a specific set of identified users';
UPDATE openchpl.test_functionality SET number = '(a)(4)(ii)(B)(2)' WHERE "name" ='Alternative: (a)(4)(ii)(B)(2) As a system administrative function';
UPDATE openchpl.test_functionality SET number = '(a)(10)(i)' WHERE "name" ='Alternative: (a)(10)(i) Drug formulary checks. Automatically check whether a drug formulary exists for a given patient and medication';
UPDATE openchpl.test_functionality SET number = '(a)(10)(ii)' WHERE "name" ='Alternative: (a)(10)(ii)  Preferred drug list checks. Automatically check whether a preferred drug list exists for a given patient and medication';
UPDATE openchpl.test_functionality SET number = '(a)(14)(iii)(A)(1)' WHERE "name" ='Alternative: (a)(14)(iii)(A)(1) The "GMDN PT Name" attribute associated with the Device Identifier in the Global Unique Device Identification Database';
UPDATE openchpl.test_functionality SET number = '(a)(14)(iii)(A)(2)' WHERE "name" ='Alternative: (a)(14)(iii)(A)(2) The "SNOMED CT Description" mapped to the attribute referenced in (a)(14)(iii)(1) (The "GMDN PT Name" attribute associated with the Device Identifier in the Global Unique Device Identification Database)';
UPDATE openchpl.test_functionality SET number = '(b)(1)(ii)(A)(5)(i)' WHERE "name" ='Alternative: (b)(1)(ii)(A)(5)(i) Be notified of the errors produced';
UPDATE openchpl.test_functionality SET number = '(b)(1)(ii)(A)(5)(ii)' WHERE "name" ='Alternative: (b)(1)(ii)(A)(5)(ii) Review the errors produced';
UPDATE openchpl.test_functionality SET number = '(b)(5)(ii)(A)(5)(i)' WHERE "name" ='Alternative: (b)(5)(ii)(A)(5)(i) Be notified of the errors produced';
UPDATE openchpl.test_functionality SET number = '(b)(5)(ii)(A)(5)(ii)' WHERE "name" ='Alternative: (b)(5)(ii)(A)(5)(ii) Review the errors produced';
UPDATE openchpl.test_functionality SET number = '(b)(6)(i)(B)(1)' WHERE "name" ='Alternative: (b)(6)(i)(B)(1) To a specific set of identified users';
UPDATE openchpl.test_functionality SET number = '(b)(6)(i)(B)(2)' WHERE "name" ='Alternative: (b)(6)(i)(B)(2) As a system administrative function';
UPDATE openchpl.test_functionality SET number = '(d)(7)(i)' WHERE "name" ='Alternative: (d)(7)(i) Technology that is designed to locally store electronic health information on end-user devices must encrypt the electronic health information stored on such devices after use of the technology on those devices stops';
UPDATE openchpl.test_functionality SET number = '(d)(7)(ii)' WHERE "name" ='Alternative: (d)(7)(ii) Technology is designed to prevent electronic health information from being locally stored on end-user devices after use of the technology on those devices stops';
UPDATE openchpl.test_functionality SET number = '(d)(9)(i)' WHERE "name" ='Alternative: (d)(9)(i) Message-level. Encrypt and integrity protect message contents in accordance with the standards specified in § 170.210(a)(2) and (c)(2)';
UPDATE openchpl.test_functionality SET number = '(d)(9)(ii)' WHERE "name" ='Alternative: (d)(9)(ii) Transport-level. Use a trusted connection in accordance with the standards specified in § 170.210(a)(2) and (c)(2)';
UPDATE openchpl.test_functionality SET number = '(g)(4)(i)(A)' WHERE "name" ='Alternative: (g)(4)(i)(A) The QMS used is established by the Federal government or a standards developing organization';
UPDATE openchpl.test_functionality SET number = '(g)(4)(i)(B)' WHERE "name" ='Alternative: (g)(4)(i)(B) The QMS used is mapped to one or more QMS established by the Federal government or standards developing organization(s)';
UPDATE openchpl.test_functionality SET number = '(g)(5)(i)' WHERE "name" ='Alternative: (g)(5)(i) When a single accessibility-centered design standard or law was used for applicable capabilities, it would only need to be identified once';
UPDATE openchpl.test_functionality SET number = '(g)(5)(ii)' WHERE "name" ='Alternative: (g)(5)(ii) When different accessibility-centered design standards and laws were applied to specific capabilities, each accessibility-centered design standard or law applied would need to be identified. This would include the application of an accessibility-centered design standard or law to some capabilities and none to others';
UPDATE openchpl.test_functionality SET number = '(g)(5)(iii)' WHERE "name" ='Alternative: (g)(5)(iii) When no accessibility-centered design standard or law was applied to all applicable capabilities such a response is acceptable to satisfy this certification criterion';
UPDATE openchpl.test_functionality SET number = '(a)(1)(ii)' WHERE "name" ='Optional: (a)(1)(ii)  Include a "reason for order" field';
UPDATE openchpl.test_functionality SET number = '(a)(2)(ii)' WHERE "name" ='Optional: (a)(2)(ii) Include a "reason for order" field';
UPDATE openchpl.test_functionality SET number = '(a)(3)(ii)' WHERE "name" ='Optional: (a)(3)(ii) Include a "reason for order" field';
UPDATE openchpl.test_functionality SET number = '(a)(13)(ii)' WHERE "name" ='Optional; (a)(13)(ii) Request that patient-specific education resources be identified in accordance with the standard in § 170.207(g)(2)';
UPDATE openchpl.test_functionality SET number = '(b)(1)(iii)(G)(1)(ii)' WHERE "name" ='Optional: (b)(1)(iii)(G)(1)(ii) When the hour, minute, and second are associated with a date of birth the technology must demonstrate that the correct time zone offset is included';
UPDATE openchpl.test_functionality SET number = '(b)(3)(iii)' WHERE "name" ='Optional: (b)(3)(iii) For each transaction listed in paragraph (b)(3)(i) of this section, the technology must be able to receive and transmit the reason for the prescription using the indication elements in the SIG Segment';
UPDATE openchpl.test_functionality SET number = '(b)(4)(vii)(A)(2)' WHERE "name" ='Optional: (b)(4)(vii)(A)(2) When the hour, minute, and second are associated with a date of birth the technology must demonstrate that the correct time zone offset is included';
UPDATE openchpl.test_functionality SET number = '(c)(3)(ii)' WHERE "name" ='Optional: (c)(3)(ii) That can be electronically accepted by CMS';
UPDATE openchpl.test_functionality SET number = '170.102(13)(ii)(C)' WHERE "name" ='Optional: CCDS: 170.102(13)(ii)(C) The patient’s BMI percentile per age and sex for youth 2-20 years of age, weight for age per length and sex for children less than 3 years of age, and head occipital-frontal circumference for children less than 3 years of age must be recorded in numerical values only in accordance with the standard specified in § 170.207(c)(3) and with the associated applicable unit of measure for the vital sign measurement in the standard specified in § 170.207(m)(1). For BMI percentile per age and sex for youth 2-20 years of age and weight for age per length and sex for children less than 3 years of age, the reference range/scale or growth curve should be included as appropriate';
UPDATE openchpl.test_functionality SET number = '170.102(19)(i)' WHERE "name" ='Optional: CCDS: 170.102(19)(i) For certification to the 2015 Edition health IT certification criteria in accordance with the "Assessment and Plan Section (V2)" of the standard specified in § 170.205(a)(4);';
UPDATE openchpl.test_functionality SET number = '170.102(19)(ii)' WHERE "name" LIKE 'Optional: CCDS: 170.102(19)(ii)%';--  For certification to the 2015 Edition health IT certification criteria in accordance with the "Assessment Section (V2)" and "Plan of Treatment Section (V2)" of the standard specified in § 170.205(a)(4).';
UPDATE openchpl.test_functionality SET number = '(a)(6)(i)' WHERE "name" ='Ambulatory: (a)(6)(i) Over multiple encounters in accordance with, at a minimum, the version of the standard specified in § 170.207(a)(4)';
UPDATE openchpl.test_functionality SET number = '(a)(7)(i)' WHERE "name" ='Ambulatory: (a)(7)(i) Over multiple encounters';
UPDATE openchpl.test_functionality SET number = '(a)(8)(i)' WHERE "name" ='Ambulatory: (a)(8)(i) Over multiple encounters';
UPDATE openchpl.test_functionality SET number = '(b)(1)(iii)(E)' WHERE "name" ='Ambulatory: (b)(1)(iii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information';
UPDATE openchpl.test_functionality SET number = '(b)(4)(v)' WHERE "name" ='Ambulatory: (b)(4)(v) The reason for referral; and referring or transitioning provider''s name and office contact information';
UPDATE openchpl.test_functionality SET number = '(b)(5)(i)(E)' WHERE "name" ='Ambulatory: (b)(5)(i)(E) The reason for referral; and referring or transitioning provider''s name and office contact information';
UPDATE openchpl.test_functionality SET number = '(b)(6)(ii)(E)' WHERE "name" ='Ambulatory: (b)(6)(ii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(A)(2)' WHERE "name" ='Ambulatory: (e)(1)(i)(A)(2) Provider''s name and office contact information';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(B)(2)(i)' WHERE "name" LIKE 'Ambulatory: (e)(1)(i)(B)(2)(i) All of the following data:%';
--(1) The Common Clinical Data Set (which should be in their English (i.e., non-coded) representation if they associate with a vocabulary/code set).
--(2) Ambulatory setting only. Provider’s name and office contact information.
--(4) Laboratory test report(s). Laboratory test report(s), including:
--(i) The information for a test report as specified all the data specified in 42 CFR 493.1291(c)(1) through (7);
--(ii)The information related to reference intervals or normal values as specified in 42 CFR 493.1291(d); and
--(iii)The information for corrected reports as specified in 42 CFR 493.1291(k)(2).
--(5) Diagnostic image report(s)';
UPDATE openchpl.test_functionality SET number = '(a)(5)(ii)' WHERE "name" ='Inpatient: (a)(5)(ii) Enable a user to record, change, and access the preliminary cause of death and date of death in the event of mortality';
UPDATE openchpl.test_functionality SET number = '(a)(6)(ii)' WHERE "name" ='Inpatient: (a)(6)(ii) For the duration of an entire hospitalization in accordance with, at a minimum, the version of the standard specified in §170.207(a)(4)';
UPDATE openchpl.test_functionality SET number = '(a)(7)(ii)' WHERE "name" ='Inpatient: (a)(7)(ii) For the duration of an entire hospitalization';
UPDATE openchpl.test_functionality SET number = '(a)(8)(ii)' WHERE "name" ='Inpatient: (a)(8)(ii) For the duration of an entire hospitalization';
UPDATE openchpl.test_functionality SET number = '(b)(1)(iii)(F)' WHERE "name" ='Inpatient: (b)(1)(iii)(F) Discharge Instructions';
UPDATE openchpl.test_functionality SET number = '(b)(4)(vi)' WHERE "name" ='Inpatient: (b)(4)(vi) Discharge Instructions';
UPDATE openchpl.test_functionality SET number = '(b)(5)(i)(F)' WHERE "name" ='Inpatient: (b)(5)(i)(F) Discharge Instructions';
UPDATE openchpl.test_functionality SET number = '(b)(6)(ii)(F)' WHERE "name" ='Inpatient: (b)(6)(ii)(F) Discharge Instructions';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(A)(3)' WHERE "name" ='Inpatient: (e)(1)(i)(A)(3) Admission and discharge dates and locations; discharge instructions; and reason(s) for hospitalization';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(B)(2)(ii)' WHERE "name" LIKE 'Inpatient: (e)(1)(i)(B)(2)(ii) All of the following data:%';
--(1) The Common Clinical Data Set (which should be in their English (i.e., non-coded) representation if they associate with a vocabulary/code set).
--(3) Inpatient setting only. Admission and discharge dates and locations; discharge instructions; and reason(s) for hospitalization.
--(5) Diagnostic image report(s)';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(B)(3)' WHERE "name" ='Inpatient: (e)(1)(i)(B)(3) Patients (and their authorized representatives) must be able to download transition of care/referral summaries that were created as a result of a transition of care (pursuant to the capability expressed in the certification criterion specified in paragraph (b)(1) of this section)';
UPDATE openchpl.test_functionality SET number = '(e)(1)(i)(C)(2)' WHERE "name" LIKE 'Inpatient: (e)(1)(i)(C)(2)%';--  Transmit transition of care/referral summaries (as a result of a transition of care/referral as referenced by (e)(1)(i)(B)(3)) selected by the patient (or their authorized representative) in  both of the following ways:
--(i) Email transmission to any email address; and
--(ii)An encrypted method of electronic transmission';



--2014 test functionality
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.314(a)(4)(iii) Plot and electronically display, upon request, growth charts for patients' WHERE "name" LIKE 'Optional: (a)(4)(iii) Plot and electronically display, upon request, growth charts for patients';
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.314(b)(1)(i)(B) Receive summary care record using the standards specified at §170.202(a) and (b) (Direct and XDM Validation)' WHERE "name" LIKE 'Optional: (b)(1)(i)(B) The standards specified in % 170.202(a) and (b)';
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.314(b)(1)(i)(C) Receive summary care record using the standards specified at §170.202(b) and (c) (SOAP Protocols)' WHERE "name" LIKE 'Optional: (b)(1)(i)(C) The standards specified in % 170.202(b) and (c)';
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.314(f)(3)(i)(B) Create syndrome-based public health surveillance information for transmission using the standard specified at §170.205(d)(3) (urgent care visit scenario)' WHERE "name" LIKE 'Optional: (f)(3)(i)(B) The standard (and applicable implementation specifications) specified in %170.205(d)(3)';
UPDATE openchpl.test_functionality SET "name" = 'Optional: (f)(7)(i) EHR technology must be able to electronically create syndrome-based public health surveillance information for electronic transmission that contains the following data: (A) Patient demographics; (B) Provider specialty; (C) Provider address; (D) Problem list; (E) Vital signs; (F) Laboratory test values/results; (G) Procedures; (H) Medication list; and (I) Insurance' WHERE "name" LIKE 'Optional: (f)(7)(i) That contains the following data: (A) Patient demographics; (B) Provider specialty; (C) Provider address; (D) Problem list; (E) Vital signs; (F) Laboratory test values/results; (G) Procedures; (H) Medication list; and (I) Insurance';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory setting: 170.314(a)(5)(i) Over multiple encounters in accordance with, at a minimum, the version of the standard specified in §170.207(a)(3)' WHERE "name" LIKE 'Ambulatory setting: (a)(5)(i) Over multiple encounters in accordance with, at a minimum, the version of the standard specified in %170.207(a)(3)';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory setting: 170.314(a)(6)(i) Over multiple encounters' WHERE "name" LIKE 'Ambulatory setting: (a)(6)(i) Over multiple encounters';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory setting: 170.314(a)(7)(i) Over multiple encounters' WHERE "name" LIKE 'Ambulatory setting: (a)(7)(i) Over multiple encounters';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory setting: 170.314(a)(8)(iii)(B)(3) When a patient''s laboratory tests and values/results are incorporated pursuant to paragraph (b)(5)(i)(A)(1) of this section' WHERE "name" LIKE 'Ambulatory setting: (a)(8)(iii)(B)(3) When a patient%s laboratory tests and values/results are incorporated pursuant to paragraph (b)(5)(i)(A)(1) of this section';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory setting: 170.314(a)(14)(vi) Patient communication preferences' WHERE "name" LIKE 'Ambulatory setting: (a)(14)(vi) Patient communication preferences';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory setting: 170.314(b)(2)(i)(E) The reason for referral; and referring or transitioning provider''s name and office contact information' WHERE "name" LIKE 'Ambulatory setting: (b)(2)(i)(E) The reason for referral; and referring or transitioning provider%s name and office contact information';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory setting: 170.314(b)(7)(v) The reason for referral; and referring or transitioning provider''s name and office contact information' WHERE "name" LIKE 'Ambulatory setting: (b)(7)(v) The reason for referral; and referring or transitioning provider%s name and office contact information';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory setting: 170.314(b)(8)(iii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information' WHERE "name" LIKE 'Ambulatory setting: (b)(8)(iii)(E) The reason for referral; and referring or transitioning provider%s name and office contact information';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory setting: 170.314(e)(1)(i)(A)(2) Provider''s name and office contact information' WHERE "name" LIKE 'Ambulatory setting: (e)(1)(i)(A)(2) Provider%s name and office contact information';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory setting: 170.314(e)(1)(i)(B)(1)(i) All of the data in the Common MU Data Set (which should be in their English (i.e., noncoded) representation if they associate with a vocabulary/code set) and the Provider''s name and office contact information' WHERE "name" LIKE 'Ambulatory setting: (e)(1)(i)(B)(1)(i) All of the data in the Common MU Data Set (which should be in their English (i.e., noncoded) representation if they associate with a vocabulary/code set) and the Provider%s name and office contact information';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory setting: 170.314(f)(3)(i) (A) The standard specified in §170.205(d)(2). (B) Optional. The standard (and applicable implementation specifications) specified in §170.205(d)(3)' WHERE "name" LIKE 'Ambulatory setting: (f)(3)(i) (A) The standard specified in %170.205(d)(2). (B) Optional. The standard (and applicable implementation specifications) specified in %170.205(d)(3)';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient setting: 170.314(a)(5)(ii) For the duration of an entire hospitalization in accordance with, at a minimum, the version of the standard specified in §170.207(a)(3)' WHERE "name" LIKE 'Inpatient setting: (a)(5)(ii) For the duration of an entire hospitalization in accordance with, at a minimum, the version of the standard specified in %170.207(a)(3)';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient setting: 170.314(a)(6)(ii) For the duration of an entire hospitalization' WHERE "name" LIKE 'Inpatient setting: (a)(6)(ii) For the duration of an entire hospitalization';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient setting: 170.314(a)(7)(ii) For the duration of an entire hospitalization' WHERE "name" LIKE 'Inpatient setting: (a)(7)(ii) For the duration of an entire hospitalization';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient setting: 170.314(b)(2)(i)(F) Discharge instructions' WHERE "name" LIKE 'Inpatient setting: (b)(2)(i)(F) Discharge instructions';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient setting: 170.314(b)(7)(vi) Discharge Instructions' WHERE "name" LIKE 'Inpatient setting: (b)(7)(vi) Discharge Instructions';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient setting: 170.314(b)(8)(iii)(F) Discharge Instructions' WHERE "name" LIKE 'Inpatient setting: (b)(8)(iii)(F) Discharge Instructions';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient setting: 170.314(e)(1)(i)(A)(3) Admission and discharge dates and locations; discharge instructions; and reason(s) for hospitalization' WHERE "name" LIKE 'Inpatient setting: (e)(1)(i)(A)(3) Admission and discharge dates and locations; discharge instructions; and reason(s) for hospitalization';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient setting: 170.314(e)(1)(i)(B)(1)(ii) All of the data in the Common MU Data Set (which should be in their English (i.e., noncoded) representation if they associate with a vocabulary/code set) and the admission and discharge dates and locations; discharge instructions; and reason(s) for hospitalization' WHERE "name" LIKE 'Inpatient setting: (e)(1)(i)(B)(1)(ii) All of the data in the Common MU Data Set (which should be in their English (i.e., noncoded) representation if they associate with a vocabulary/code set) and the admission and discharge dates and locations; discharge instructions; and reason(s) for hospitalization';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient setting: 170.314(e)(1)(i)(B)(2) Electronically download transition of care/referral summaries that were created as a result of a transition of care (pursuant to the capability expressed in the certification criterion adopted at paragraph (b)(2) of this section)' WHERE "name" LIKE 'Inpatient setting: (e)(1)(i)(B)(2) Electronically download transition of care/referral summaries that were created as a result of a transition of care (pursuant to the capability expressed in the certification criterion adopted at paragraph (b)(2) of this section)';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient setting: 170.314(e)(1)(i)(C)(2) Electronically transmit transition of care/referral summaries (as a result of a transition of care/referral) selected by the patient (or their authorized representative) in accordance with at least one of the following: (i) The standard specified in §170.202(a). (ii) Through a method that conforms to the standard specified at §170.202(d) and that leads to such summary being processed by a service that has implemented the standard specified in §170.202(a)' WHERE "name" LIKE 'Inpatient setting: (e)(1)(i)(C)(2) Electronically transmit transition of care/referral summaries (as a result of a transition of care/referral) selected by the patient (or their authorized representative) in accordance with at least one of the following: (i) The standard specified in %170.202(a). (ii) Through a method that conforms to the standard specified at %170.202(d) and that leads to such summary being processed by a service that has implemented the standard specified in %170.202(a)';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient setting: 170.314(f)(3)(ii)  The standard (and applicable implementation specifications) specified in §170.205(d)(3)' WHERE "name" LIKE 'Inpatient setting: (f)(3)(ii)  The standard (and applicable implementation specifications) specified in %170.205(d)(3)';

--2015 test functionality
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(a)(4)(ii)(B)(1) To a specific set of identified users' WHERE "name" LIKE 'Alternative: (a)(4)(ii)(B)(1) To a specific set of identified users';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(a)(4)(ii)(B)(2) As a system administrative function' WHERE "name" LIKE 'Alternative: (a)(4)(ii)(B)(2) As a system administrative function';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(a)(10)(i) Drug formulary checks. Automatically check whether a drug formulary exists for a given patient and medication' WHERE "name" LIKE 'Alternative: (a)(10)(i) Drug formulary checks. Automatically check whether a drug formulary exists for a given patient and medication';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(a)(10)(ii)  Preferred drug list checks. Automatically check whether a preferred drug list exists for a given patient and medication' WHERE "name" LIKE 'Alternative: (a)(10)(ii)  Preferred drug list checks. Automatically check whether a preferred drug list exists for a given patient and medication';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(a)(14)(iii)(A)(1) The "GMDN PT Name" attribute associated with the Device Identifier in the Global Unique Device Identification Database' WHERE "name" LIKE 'Alternative: (a)(14)(iii)(A)(1) The "GMDN PT Name" attribute associated with the Device Identifier in the Global Unique Device Identification Database';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(a)(14)(iii)(A)(2) The "SNOMED CT Description" mapped to the attribute referenced in (a)(14)(iii)(1) (The "GMDN PT Name" attribute associated with the Device Identifier in the Global Unique Device Identification Database)' WHERE "name" LIKE 'Alternative: (a)(14)(iii)(A)(2) The "SNOMED CT Description" mapped to the attribute referenced in (a)(14)(iii)(1) (The "GMDN PT Name" attribute associated with the Device Identifier in the Global Unique Device Identification Database)';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(b)(1)(ii)(A)(5)(i) Be notified of the errors produced' WHERE "name" LIKE 'Alternative: (b)(1)(ii)(A)(5)(i) Be notified of the errors produced';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(b)(1)(ii)(A)(5)(ii) Review the errors produced' WHERE "name" LIKE 'Alternative: (b)(1)(ii)(A)(5)(ii) Review the errors produced';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(b)(5)(ii)(A)(5)(i) Be notified of the errors produced' WHERE "name" LIKE 'Alternative: (b)(5)(ii)(A)(5)(i) Be notified of the errors produced';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(b)(5)(ii)(A)(5)(ii) Review the errors produced' WHERE "name" LIKE 'Alternative: (b)(5)(ii)(A)(5)(ii) Review the errors produced';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(b)(6)(i)(B)(1) To a specific set of identified users' WHERE "name" LIKE 'Alternative: (b)(6)(i)(B)(1) To a specific set of identified users';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(b)(6)(i)(B)(2) As a system administrative function' WHERE "name" LIKE 'Alternative: (b)(6)(i)(B)(2) As a system administrative function';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(d)(7)(i) Technology that is designed to locally store electronic health information on end-user devices must encrypt the electronic health information stored on such devices after use of the technology on those devices stops' WHERE "name" LIKE 'Alternative: (d)(7)(i) Technology that is designed to locally store electronic health information on end-user devices must encrypt the electronic health information stored on such devices after use of the technology on those devices stops';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(d)(7)(ii) Technology is designed to prevent electronic health information from being locally stored on end-user devices after use of the technology on those devices stops' WHERE "name" LIKE 'Alternative: (d)(7)(ii) Technology is designed to prevent electronic health information from being locally stored on end-user devices after use of the technology on those devices stops';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(d)(9)(i) Message-level. Encrypt and integrity protect message contents in accordance with the standards specified in § 170.210(a)(2) and (c)(2)' WHERE "name" LIKE 'Alternative: (d)(9)(i) Message-level. Encrypt and integrity protect message contents in accordance with the standards specified in % 170.210(a)(2) and (c)(2)';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(d)(9)(ii) Transport-level. Use a trusted connection in accordance with the standards specified in § 170.210(a)(2) and (c)(2)' WHERE "name" LIKE 'Alternative: (d)(9)(ii) Transport-level. Use a trusted connection in accordance with the standards specified in % 170.210(a)(2) and (c)(2)';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(g)(4)(i)(A) The QMS used is established by the Federal government or a standards developing organization' WHERE "name" LIKE 'Alternative: (g)(4)(i)(A) The QMS used is established by the Federal government or a standards developing organization';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(g)(4)(i)(B) The QMS used is mapped to one or more QMS established by the Federal government or standards developing organization(s)' WHERE "name" LIKE 'Alternative: (g)(4)(i)(B) The QMS used is mapped to one or more QMS established by the Federal government or standards developing organization(s)';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(g)(5)(i) When a single accessibility-centered design standard or law was used for applicable capabilities, it would only need to be identified once' WHERE "name" LIKE 'Alternative: (g)(5)(i) When a single accessibility-centered design standard or law was used for applicable capabilities, it would only need to be identified once';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(g)(5)(ii) When different accessibility-centered design standards and laws were applied to specific capabilities, each accessibility-centered design standard or law applied would need to be identified. This would include the application of an accessibility-centered design standard or law to some capabilities and none to others' WHERE "name" LIKE 'Alternative: (g)(5)(ii) When different accessibility-centered design standards and laws were applied to specific capabilities, each accessibility-centered design standard or law applied would need to be identified. This would include the application of an accessibility-centered design standard or law to some capabilities and none to others';
UPDATE openchpl.test_functionality SET "name" = 'Alternative: 170.315(g)(5)(iii) When no accessibility-centered design standard or law was applied to all applicable capabilities such a response is acceptable to satisfy this certification criterion' WHERE "name" LIKE 'Alternative: (g)(5)(iii) When no accessibility-centered design standard or law was applied to all applicable capabilities such a response is acceptable to satisfy this certification criterion';
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.315(a)(1)(ii)  Include a "reason for order" field' WHERE "name" LIKE 'Optional: (a)(1)(ii)  Include a "reason for order" field';
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.315(a)(2)(ii) Include a "reason for order" field' WHERE "name" LIKE 'Optional: (a)(2)(ii) Include a "reason for order" field';
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.315(a)(3)(ii) Include a "reason for order" field' WHERE "name" LIKE 'Optional: (a)(3)(ii) Include a "reason for order" field';
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.315(a)(13)(ii) Request that patient-specific education resources be identified in accordance with the standard in § 170.207(g)(2)' WHERE "name" LIKE 'Optional; (a)(13)(ii) Request that patient-specific education resources be identified in accordance with the standard in % 170.207(g)(2)';
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.315(b)(1)(iii)(G)(1)(ii) When the hour, minute, and second are associated with a date of birth the technology must demonstrate that the correct time zone offset is included' WHERE "name" LIKE 'Optional: (b)(1)(iii)(G)(1)(ii) When the hour, minute, and second are associated with a date of birth the technology must demonstrate that the correct time zone offset is included';
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.315(b)(3)(iii) For each transaction listed in paragraph (b)(3)(i) of this section, the technology must be able to receive and transmit the reason for the prescription using the indication elements in the SIG Segment' WHERE "name" LIKE 'Optional: (b)(3)(iii) For each transaction listed in paragraph (b)(3)(i) of this section, the technology must be able to receive and transmit the reason for the prescription using the indication elements in the SIG Segment';
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.315(b)(4)(vii)(A)(2) When the hour, minute, and second are associated with a date of birth the technology must demonstrate that the correct time zone offset is included' WHERE "name" LIKE 'Optional: (b)(4)(vii)(A)(2) When the hour, minute, and second are associated with a date of birth the technology must demonstrate that the correct time zone offset is included';
UPDATE openchpl.test_functionality SET "name" = 'Optional: 170.315(c)(3)(ii) That can be electronically accepted by CMS' WHERE "name" LIKE 'Optional: (c)(3)(ii) That can be electronically accepted by CMS';
UPDATE openchpl.test_functionality SET "name" = 'Optional: Common Clinical Data Set 170.102(13)(ii)(C) The patient''s BMI percentile per age and sex for youth 2-20 years of age, weight for age per length and sex for children less than 3 years of age, and head occipital-frontal circumference for children less than 3 years of age must be recorded in numerical values only in accordance with the standard specified in § 170.207(c)(3) and with the associated applicable unit of measure for the vital sign measurement in the standard specified in § 170.207(m)(1). For BMI percentile per age and sex for youth 2-20 years of age and weight for age per length and sex for children less than 3 years of age, the reference range/scale or growth curve should be included as appropriate' WHERE "name" LIKE 'Optional: CCDS: 170.102(13)(ii)(C) The patient''s BMI percentile per age and sex for youth 2-20 years of age, weight for age per length and sex for children less than 3 years of age, and head occipital-frontal circumference for children less than 3 years of age must be recorded in numerical values only in accordance with the standard specified in % 170.207(c)(3) and with the associated applicable unit of measure for the vital sign measurement in the standard specified in % 170.207(m)(1). For BMI percentile per age and sex for youth 2-20 years of age and weight for age per length and sex for children less than 3 years of age, the reference range/scale or growth curve should be included as appropriate';
UPDATE openchpl.test_functionality SET "name" = 'Optional: Common Clinical Data Set 170.102(19)(i) For certification to the 2015 Edition health IT certification criteria in accordance with the "Assessment and Plan Section (V2)" of the standard specified in § 170.205(a)(4);' WHERE "name" LIKE 'Optional: CCDS: 170.102(19)(i) For certification to the 2015 Edition health IT certification criteria in accordance with the "Assessment and Plan Section (V2)" of the standard specified in % 170.205(a)(4);';
UPDATE openchpl.test_functionality SET "name" = 'Optional: Common Clincial Data Set 170.102(19)(ii)  For certification to the 2015 Edition health IT certification criteria in accordance with the "Assessment Section (V2)" and "Plan of Treatment Section (V2)" of the standard specified in § 170.205(a)(4). ' WHERE "name" LIKE 'Optional: CCDS: 170.102(19)(ii)  For certification to the 2015 Edition health IT certification criteria in accordance with the "Assessment Section (V2)" and "Plan of Treatment Section (V2)" of the standard specified in % 170.205(a)(4). ';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory: 170.315(a)(6)(i) Over multiple encounters in accordance with, at a minimum, the version of the standard specified in § 170.207(a)(4)' WHERE "name" LIKE 'Ambulatory: (a)(6)(i) Over multiple encounters in accordance with, at a minimum, the version of the standard specified in % 170.207(a)(4)';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory: 170.315(a)(7)(i) Over multiple encounters' WHERE "name" LIKE 'Ambulatory: (a)(7)(i) Over multiple encounters';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory: 170.315(a)(8)(i) Over multiple encounters' WHERE "name" LIKE 'Ambulatory: (a)(8)(i) Over multiple encounters';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory: 170.315(b)(1)(iii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information' WHERE "name" LIKE 'Ambulatory: (b)(1)(iii)(E) The reason for referral; and referring or transitioning provider%s name and office contact information';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory: 170.315(b)(4)(v) The reason for referral; and referring or transitioning provider''s name and office contact information' WHERE "name" LIKE 'Ambulatory: (b)(4)(v) The reason for referral; and referring or transitioning provider%s name and office contact information';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory: 170.315(b)(5)(i)(E) The reason for referral; and referring or transitioning provider''s name and office contact information' WHERE "name" LIKE 'Ambulatory: (b)(5)(i)(E) The reason for referral; and referring or transitioning provider%s name and office contact information';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory: 170.315(b)(6)(ii)(E) The reason for referral; and referring or transitioning provider''s name and office contact information' WHERE "name" LIKE 'Ambulatory: (b)(6)(ii)(E) The reason for referral; and referring or transitioning provider%s name and office contact information';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory: 170.315(e)(1)(i)(A)(2) Provider''s name and office contact information' WHERE "name" LIKE 'Ambulatory: (e)(1)(i)(A)(2) Provider%s name and office contact information';
UPDATE openchpl.test_functionality SET "name" = 'Ambulatory: 170.315(e)(1)(i)(B)(2)(i) All of the following data:
(1) The Common Clinical Data Set (which should be in their English (i.e., non-coded) representation if they associate with a vocabulary/code set).
(2) Ambulatory setting only. Provider''s name and office contact information.
(4) Laboratory test report(s). Laboratory test report(s), including:
(i) The information for a test report as specified all the data specified in 42 CFR 493.1291(c)(1) through (7);
(ii)The information related to reference intervals or normal values as specified in 42 CFR 493.1291(d); and
(iii)The information for corrected reports as specified in 42 CFR 493.1291(k)(2).
(5) Diagnostic image report(s)' WHERE "name" LIKE 'Ambulatory: (e)(1)(i)(B)(2)(i) All of the following data:%';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(a)(5)(ii) Enable a user to record, change, and access the preliminary cause of death and date of death in the event of mortality' WHERE "name" LIKE 'Inpatient: (a)(5)(ii) Enable a user to record, change, and access the preliminary cause of death and date of death in the event of mortality';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(a)(6)(ii) For the duration of an entire hospitalization in accordance with, at a minimum, the version of the standard specified in §170.207(a)(4)' WHERE "name" LIKE 'Inpatient: (a)(6)(ii) For the duration of an entire hospitalization in accordance with, at a minimum, the version of the standard specified in %170.207(a)(4)';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(a)(7)(ii) For the duration of an entire hospitalization' WHERE "name" LIKE 'Inpatient: (a)(7)(ii) For the duration of an entire hospitalization';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(a)(8)(ii) For the duration of an entire hospitalization' WHERE "name" LIKE 'Inpatient: (a)(8)(ii) For the duration of an entire hospitalization';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(b)(1)(iii)(F) Discharge Instructions' WHERE "name" LIKE 'Inpatient: (b)(1)(iii)(F) Discharge Instructions';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(b)(4)(vi) Discharge Instructions' WHERE "name" LIKE 'Inpatient: (b)(4)(vi) Discharge Instructions';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(b)(5)(i)(F) Discharge Instructions' WHERE "name" LIKE 'Inpatient: (b)(5)(i)(F) Discharge Instructions';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(b)(6)(ii)(F) Discharge Instructions' WHERE "name" LIKE 'Inpatient: (b)(6)(ii)(F) Discharge Instructions';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(e)(1)(i)(A)(3) Admission and discharge dates and locations; discharge instructions; and reason(s) for hospitalization' WHERE "name" LIKE 'Inpatient: (e)(1)(i)(A)(3) Admission and discharge dates and locations; discharge instructions; and reason(s) for hospitalization';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(e)(1)(i)(B)(2)(ii) All of the following data:
(1) The Common Clinical Data Set (which should be in their English (i.e., non-coded) representation if they associate with a vocabulary/code set).
(3) Inpatient setting only. Admission and discharge dates and locations; discharge instructions; and reason(s) for hospitalization.
(5) Diagnostic image report(s)' WHERE "name" LIKE 'Inpatient: (e)(1)(i)(B)(2)(ii) All of the following data:%';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(e)(1)(i)(B)(3) Patients (and their authorized representatives) must be able to download transition of care/referral summaries that were created as a result of a transition of care (pursuant to the capability expressed in the certification criterion specified in paragraph (b)(1) of this section)' WHERE "name" LIKE 'Inpatient: (e)(1)(i)(B)(3) Patients (and their authorized representatives) must be able to download transition of care/referral summaries that were created as a result of a transition of care (pursuant to the capability expressed in the certification criterion specified in paragraph (b)(1) of this section)';
UPDATE openchpl.test_functionality SET "name" = 'Inpatient: 170.315(e)(1)(i)(C)(2)  Transmit transition of care/referral summaries (as a result of a transition of care/referral as referenced by (e)(1)(i)(B)(3)) selected by the patient (or their authorized representative) in  both of the following ways:
(i) Email transmission to any email address; and
(ii)An encrypted method of electronic transmission' WHERE "name" LIKE 'Inpatient: (e)(1)(i)(C)(2)  Transmit transition of care/referral summaries (as a result of a transition of care/referral as referenced by (e)(1)(i)(B)(3)) selected by the patient (or their authorized representative) in  both of the following ways:%';
UPDATE openchpl.test_standard SET "name" = 'DIRECT: Applicability Statement for Secure Health Transport, Version 1.1, July 10, 2012' WHERE "name" LIKE 'DIRECT: Applicability Statement for Secure Health Transport, Version 1.1, July 10, 2012';
UPDATE openchpl.test_standard SET "name" = 'XDR and XDM for Direct Messaging Specification, Version 1, March 9, 2011' WHERE "name" LIKE 'XDR and XDM for Direct Messaging Specification, Version 1, March 9, 2011';
UPDATE openchpl.test_standard SET "name" = 'Transport and Security Specification, Version 1.0, June 19, 2012' WHERE "name" LIKE 'Transport and Security Specification, Version 1.0, June 19, 2012';
UPDATE openchpl.test_standard SET "name" = 'Implementation Guide for Direct Edge Protocols, Version 1.1, June 25, 2014' WHERE "name" LIKE 'Implementation Guide for Direct Edge Protocols, Version 1.1, June 25, 2014';
UPDATE openchpl.test_standard SET "name" = 'Web Content Accessibility Guidelines (WCAG) 2.0, December 11, 2008' WHERE "name" LIKE 'Web Content Accessibility Guidelines (WCAG) 2.0, December 11, 2008';
UPDATE openchpl.test_standard SET "name" = 'HL7 Version 3 Standard: Context-Aware Retrieval Application (Infobutton); Release 1, July 2010' WHERE "name" LIKE 'HL7 Version 3 Standard: Context-Aware Retrieval Application (Infobutton); Release 1, July 2010';
UPDATE openchpl.test_standard SET "name" = 'HL7 Version 3 Implementation Guide: URL-Based Implementations of the Context-Aware Information Retrieval (Infobutton) Domain, Release 3, December 2010' WHERE "name" LIKE 'HL7 Version 3 Implementation Guide: URL-Based Implementations of the Context-Aware Information Retrieval (Infobutton) Domain, Release 3, December 2010';
UPDATE openchpl.test_standard SET "name" = 'HL7 Version 3 Implementation Guide: Context-Aware Knowledge Retrieval (Infobutton) Service-Oriented Architecture Implementation Guide, Release 1, HL7 Draft Standard for Trial Use, March 2011' WHERE "name" LIKE 'HL7 Version 3 Implementation Guide: Context-Aware Knowledge Retrieval (Infobutton) Service-Oriented Architecture Implementation Guide, Release 1, HL7 Draft Standard for Trial Use, March 2011';
UPDATE openchpl.test_standard SET "name" = 'Data Element Catalog, Version 1.1 October 2012' WHERE "name" LIKE 'Data Element Catalog, Version 1.1 October 2012';
UPDATE openchpl.test_standard SET "name" = 'HITSP Summary Documents Using HL7 Continuity of Care Document (CCD) Component, HITSP/C32, July 8, 2009, Version 2.5' WHERE "name" LIKE 'HITSP Summary Documents Using HL7 Continuity of Care Document (CCD) Component, HITSP/C32, July 8, 2009, Version 2.5';
UPDATE openchpl.test_standard SET "name" = 'Health Level Seven Implementation Guide: Clinical Document Architecture (CDA) Release 2—Continuity of Care Document (CCD), April 01, 2007' WHERE "name" LIKE 'Health Level Seven Implementation Guide: Clinical Document Architecture (CDA) Release 2—Continuity of Care Document (CCD), April 01, 2007';
UPDATE openchpl.test_standard SET "name" = 'ASTM E2369–05: Standard Specification for Continuity of Care Record (CCR), year of adoption 2005, ASTM approved July 17, 2006' WHERE "name" LIKE 'ASTM E2369–05: Standard Specification for Continuity of Care Record (CCR), year of adoption 2005, ASTM approved July 17, 2006';
UPDATE openchpl.test_standard SET "name" = 'ASTM E2369–05 (Adjunct to E2369): Standard Specification Continuity of Care Record,—Final Version 1.0 (V1.0), November 7, 2005' WHERE "name" LIKE 'ASTM E2369–05 (Adjunct to E2369): Standard Specification Continuity of Care Record,—Final Version 1.0 (V1.0), November 7, 2005';
UPDATE openchpl.test_standard SET "name" = 'HL7 Implementation Guide for CDA® Release 2: IHE Health Story Consolidation, DSTU Release 1.1 (US Realm) Draft Standard for Trial Use July 2012' WHERE "name" LIKE 'HL7 Implementation Guide for CDA® Release 2: IHE Health Story Consolidation, DSTU Release 1.1 (US Realm) Draft Standard for Trial Use July 2012';
UPDATE openchpl.test_standard SET "name" = 'SCRIPT Standard, Implementation Guide, Version 10.6, October, 2008, (Approval date for ANSI: November 12, 2008)' WHERE "name" LIKE 'SCRIPT Standard, Implementation Guide, Version 10.6, October, 2008, (Approval date for ANSI: November 12, 2008)';
UPDATE openchpl.test_standard SET "name" = 'PHIN Messaging Guide for Syndromic Surveillance: Emergency Department and Urgent Care Data, ADT Messages A01, A03, A04, and A08, HL7 Version 2.5.1 (Version 2.3.1 Compatible), Release 1.1, August 2012' WHERE "name" LIKE 'PHIN Messaging Guide for Syndromic Surveillance: Emergency Department and Urgent Care Data, ADT Messages A01, A03, A04, and A08, HL7 Version 2.5.1 (Version 2.3.1 Compatible), Release 1.1, August 2012';
UPDATE openchpl.test_standard SET "name" = 'Conformance Clarification for EHR Certification of Electronic Syndromic Surveillance, ADT MESSAGES A01, A03, A04, and A08, HL7 Version 2.5.1, Addendum to PHIN Messaging Guide for Syndromic Surveillance: Emergency Department and Urgent Care Data (Release 1.1), August 2012' WHERE "name" LIKE 'Conformance Clarification for EHR Certification of Electronic Syndromic Surveillance, ADT MESSAGES A01, A03, A04, and A08, HL7 Version 2.5.1, Addendum to PHIN Messaging Guide for Syndromic Surveillance: Emergency Department and Urgent Care Data (Release 1.1), August 2012';
UPDATE openchpl.test_standard SET "name" = 'Health Level Seven Messaging Standard Version 2.5.1 (HL7 2.5.1), An Application Protocol for Electronic Data Exchange in Healthcare Environments, February 21, 2007' WHERE "name" LIKE 'Health Level Seven Messaging Standard Version 2.5.1 (HL7 2.5.1), An Application Protocol for Electronic Data Exchange in Healthcare Environments, February 21, 2007';
UPDATE openchpl.test_standard SET "name" = 'HL7 2.5.1 Implementation Guide for Immunization Messaging, Release 1.4, August 1, 2012' WHERE "name" LIKE 'HL7 2.5.1 Implementation Guide for Immunization Messaging, Release 1.4, August 1, 2012';
UPDATE openchpl.test_standard SET "name" = 'Health Level Seven Messaging Standard Version 2.5.1 (HL7 2.5.1), An Application Protocol for Electronic Data Exchange in Healthcare Environments, February 21, 2007' WHERE "name" LIKE 'Health Level Seven Messaging Standard Version 2.5.1 (HL7 2.5.1), An Application Protocol for Electronic Data Exchange in Healthcare Environments, February 21, 2007';
UPDATE openchpl.test_standard SET "name" = 'HL7 v2.5.1 IG: Electronic Laboratory Reporting to Public Health (US Realm), Release 1 Errata and Clarifications, September, 29, 2011' WHERE "name" LIKE 'HL7 v2.5.1 IG: Electronic Laboratory Reporting to Public Health (US Realm), Release 1 Errata and Clarifications, September, 29, 2011';
UPDATE openchpl.test_standard SET "name" = 'ELR 2.5.1 Clarification Document for EHR Technology Certification, July 16, 2012' WHERE "name" LIKE 'ELR 2.5.1 Clarification Document for EHR Technology Certification, July 16, 2012';
UPDATE openchpl.test_standard SET "name" = 'Health Level Seven Messaging Standard Version 2.5.1 (HL7 2.5.1), An Application Protocol for Electronic Data Exchange in Healthcare Environments, February 21, 2007' WHERE "name" LIKE 'Health Level Seven Messaging Standard Version 2.5.1 (HL7 2.5.1), An Application Protocol for Electronic Data Exchange in Healthcare Environments, February 21, 2007';
UPDATE openchpl.test_standard SET "name" = 'HL7 Version 2.5.1 Implementation Guide: Electronic Laboratory Reporting to Public Health, Release 1 (US Realm) HL7 Version 2.5.1: ORU^R01, HL7 Informative Document, February, 2010' WHERE "name" LIKE 'HL7 Version 2.5.1 Implementation Guide: Electronic Laboratory Reporting to Public Health, Release 1 (US Realm) HL7 Version 2.5.1: ORU^R01, HL7 Informative Document, February, 2010';
UPDATE openchpl.test_standard SET "name" = 'HL7 Implementation Guide for CDA® Release 2: Quality Reporting Document Architecture, DTSU Release 2 (Universal Realm), Draft Standard for Trial Use, July 2012' WHERE "name" LIKE 'HL7 Implementation Guide for CDA® Release 2: Quality Reporting Document Architecture, DTSU Release 2 (Universal Realm), Draft Standard for Trial Use, July 2012';
UPDATE openchpl.test_standard SET "name" = 'Implementation Guide for Ambulatory Healthcare Provider Reporting to Central Cancer Registries, HL7 Clinical Document Architecture (CDA), Release 1.0, August 2012' WHERE "name" LIKE 'Implementation Guide for Ambulatory Healthcare Provider Reporting to Central Cancer Registries, HL7 Clinical Document Architecture (CDA), Release 1.0, August 2012';
UPDATE openchpl.test_standard SET "name" = 'HL7 Clinical Document Architecture, Release 2.0, Normative Edition, May 2005' WHERE "name" LIKE 'HL7 Clinical Document Architecture, Release 2.0, Normative Edition, May 2005';
UPDATE openchpl.test_standard SET "name" = 'HL7 Version 2.5.1 Implementation Guide: S&I Framework Lab Results Interface, Release 1 - US Realm [HL7 Version 2.5.1: ORU^R01] Draft Standard for Trial Use, July 2012' WHERE "name" LIKE 'HL7 Version 2.5.1 Implementation Guide: S&I Framework Lab Results Interface, Release 1 - US Realm [HL7 Version 2.5.1: ORU^R01] Draft Standard for Trial Use, July 2012';
UPDATE openchpl.test_standard SET "name" = 'HL7 Implementation Guide for CDA® Release 2: Quality Reporting Document Architecture—Category III, DSTU Release 1 (US Realm) Draft Standard for Trial Use, November 2012' WHERE "name" LIKE 'HL7 Implementation Guide for CDA® Release 2: Quality Reporting Document Architecture—Category III, DSTU Release 1 (US Realm) Draft Standard for Trial Use, November 2012';
UPDATE openchpl.test_standard SET "name" = 'International Health Terminology Standards Development Organisation (IHTSDO) Systematized Nomenclature of Medicine Clinical Terms (SNOMED CT®) International Release July 31, 2012' WHERE "name" LIKE 'International Health Terminology Standards Development Organisation (IHTSDO) Systematized Nomenclature of Medicine Clinical Terms (SNOMED CT®) International Release July 31, 2012';
UPDATE openchpl.test_standard SET "name" = 'US Extension to SNOMED CT® March 2012 Release' WHERE "name" LIKE 'US Extension to SNOMED CT® March 2012 Release';
UPDATE openchpl.test_standard SET "name" = 'CPT-4' WHERE "name" LIKE 'CPT-4';
UPDATE openchpl.test_standard SET "name" = 'HCPCS' WHERE "name" LIKE 'HCPCS';
UPDATE openchpl.test_standard SET "name" = 'CDT' WHERE "name" LIKE 'CDT';
UPDATE openchpl.test_standard SET "name" = 'ICD-10-PCS' WHERE "name" LIKE 'ICD-10-PCS';
UPDATE openchpl.test_standard SET "name" = 'Logical Observation Identifiers Names and Codes (LOINC®) Database version 2.40,Released June 2012' WHERE "name" LIKE 'Logical Observation Identifiers Names and Codes (LOINC®) Database version 2.40,Released June 2012';
UPDATE openchpl.test_standard SET "name" = 'RxNorm, August 6, 2012 Full Release Update' WHERE "name" LIKE 'RxNorm, August 6, 2012 Full Release Update';
UPDATE openchpl.test_standard SET "name" = 'IIS: HL7 Standard Code Set CVX -- Vaccines Administered, updates through July 11, 2012' WHERE "name" LIKE 'IIS: HL7 Standard Code Set CVX -- Vaccines Administered, updates through July 11, 2012';
UPDATE openchpl.test_standard SET "name" = 'OMB standards for Maintaining, Collecting, and Presenting Federal Data on Race and Ethnicity, Statistical Policy Directive No. 15, Oct 30, 1997' WHERE "name" LIKE 'OMB standards for Maintaining, Collecting, and Presenting Federal Data on Race and Ethnicity, Statistical Policy Directive No. 15, Oct 30, 1997';
UPDATE openchpl.test_standard SET "name" = 'ISO 639-2. Codes for the Representation of Names of Languages Part 2: Alpha-3 Code, April 8, 2011' WHERE "name" LIKE 'ISO 639-2. Codes for the Representation of Names of Languages Part 2: Alpha-3 Code, April 8, 2011';
UPDATE openchpl.test_standard SET "name" = 'ICD-10-CM' WHERE "name" LIKE 'ICD-10-CM';
UPDATE openchpl.test_standard SET "name" = 'HL7 Version 3 Standard: Clinical Genomics; Pedigree, Release 1, Edition 2011, March 2012' WHERE "name" LIKE 'HL7 Version 3 Standard: Clinical Genomics; Pedigree, Release 1, Edition 2011, March 2012';
UPDATE openchpl.test_standard SET "name" = 'Annex A: Approved Security Functions for FIPS PUB 140-2, Security Requirements for Cryptographic Modules, Draft, May 30, 2012' WHERE "name" LIKE 'Annex A: Approved Security Functions for FIPS PUB 140-2, Security Requirements for Cryptographic Modules, Draft, May 30, 2012';
UPDATE openchpl.test_standard SET "name" = 'Annex A: Approved Security Functions for FIPS PUB 140-2, Security Requirements for Cryptographic Modules, Draft, May 30, 2012' WHERE "name" LIKE 'Annex A: Approved Security Functions for FIPS PUB 140-2, Security Requirements for Cryptographic Modules, Draft, May 30, 2012';
UPDATE openchpl.test_standard SET "name" = 'RFC 1305: Network Time Protocol (Version 3) Specification, Implementation and Analysis, March 1992' WHERE "name" LIKE 'RFC 1305: Network Time Protocol (Version 3) Specification, Implementation and Analysis, March 1992';
UPDATE openchpl.test_standard SET "name" = 'RFC 5905: Network Time Protocol Version 4: Protocol and Algorithms Specification, June 2010' WHERE "name" LIKE 'RFC 5905: Network Time Protocol Version 4: Protocol and Algorithms Specification, June 2010';
UPDATE openchpl.test_standard SET "name" = 'ASTM E2147-01 (Reapproved 2009) Standard Specification for Audit and Disclosure Logs for Use in Health Information Systems, approved September 1, 2009' WHERE "name" LIKE 'ASTM E2147-01 (Reapproved 2009) Standard Specification for Audit and Disclosure Logs for Use in Health Information Systems, approved September 1, 2009';

--2015 test standardsUPDATE openchpl.test_standard SET "name" = 'CDT' WHERE "name" LIKE 'CDT';
UPDATE openchpl.test_standard SET "name" = 'CPT-4' WHERE "name" LIKE 'CPT-4';
UPDATE openchpl.test_standard SET "name" = 'ASTM E2147 (Reapproved 2013) ' WHERE "name" LIKE 'ASTM E2147 (Reapproved 2013) ';
UPDATE openchpl.test_standard SET "name" = 'CDC Race and Ethnicity Code Set Version 1.0 (March 2000)' WHERE "name" LIKE 'CDC Race and Ethnicity Code Set Version 1.0 (March 2000)';
UPDATE openchpl.test_standard SET "name" = 'National Drug Code Directory – Vaccine NDC Linker, updates through August 17, 2015' WHERE "name" LIKE 'National Drug Code Directory – Vaccine NDC Linker, updates through August 17, 2015';
UPDATE openchpl.test_standard SET "name" = 'ICD-10-PCS' WHERE "name" LIKE 'ICD-10-PCS';
UPDATE openchpl.test_standard SET "name" = 'ICD-10-CM' WHERE "name" LIKE 'ICD-10-CM';
UPDATE openchpl.test_standard SET "name" = 'Crosswalk: Medicare Provider/Supplier to Healthcare Provider Taxonomy (updated April 2, 2015)' WHERE "name" LIKE 'Crosswalk: Medicare Provider/Supplier to Healthcare Provider Taxonomy (updated April 2, 2015)';
UPDATE openchpl.test_standard SET "name" = 'Record treatment, payment, and health care operations disclosures' WHERE "name" LIKE 'Record treatment, payment, and health care operations disclosures';
UPDATE openchpl.test_standard SET "name" = 'Birth sex must be coded in accordance with HL7 Version 3 Standard, Value Sets for AdminstrativeGender and NullFlavor attributed as follows [PDF - 59 KB]:
(1) Male. M
(2) Female. F
(3) Unknown. nullFlavor UNK 1' WHERE "name" LIKE 'Birth sex must be coded in accordance with HL7 Version 3 Standard, Value Sets for AdminstrativeGender and NullFlavor attributed as follows [PDF - 59 KB]:%';
UPDATE openchpl.test_standard SET "name" = 'HL7 Version 3 Standard, Value Sets for AdminstrativeGender and NullFlavor attributed as follows:
* Something else, please describe. nullFlavor OTH
* Don''t know. nullFlavor UNK
* Choose not to disclose. nullFlavor ASKU
* Additional gender category or other, please specify. nullFlavor OTH
* Choose not to disclose. nullFlavor ASKU' WHERE "name" LIKE 'HL7 Version 3 Standard, Value Sets for AdminstrativeGender and NullFlavor attributed as follows:%';
UPDATE openchpl.test_standard SET "name" = 'HL7 Version 3 Standard: Context Aware Knowledge Retrieval Application. ("Infobutton"), Knowledge Request, Release 2, 2014 Release
HL7 Implementation Guide: Service-Oriented Architecture Implementations of the Context-aware Knowledge Retrieval (Infobutton) Domain, Release 1, August 9, 2013' WHERE "name" LIKE 'HL7 Version 3 Standard: Context Aware Knowledge Retrieval Application. ("Infobutton"), Knowledge Request, Release 2, 2014 Release%';
UPDATE openchpl.test_standard SET "name" = 'HL7 Version 3 Standard: Context Aware Retrieval Application ("Infobutton"), Knowledge Request, Release 2, 2014 Release
HL7 Version 3 Implementation Guide: Context-Aware Knowledge Retrieval (Infobutton), Release 4, June 13, 2014' WHERE "name" LIKE 'HL7 Version 3 Standard: Context Aware Retrieval Application ("Infobutton"), Knowledge Request, Release 2, 2014 Release%';
UPDATE openchpl.test_standard SET "name" = 'IHE IT Infrastructure Technical Framework Volume 2b (ITI TF-2b) Transactions Part B – Sections 3.29 – 3.43, Revision 7.0, August 10, 2010' WHERE "name" LIKE 'IHE IT Infrastructure Technical Framework Volume 2b (ITI TF-2b) Transactions Part B – Sections 3.29 – 3.43, Revision 7.0, August 10, 2010';
UPDATE openchpl.test_standard SET "name" = 'HL7 Implementation Guide for CDA® Release 2: IHE Health Story Consolidation, Release 1.1 - US Realm' WHERE "name" LIKE 'HL7 Implementation Guide for CDA® Release 2: IHE Health Story Consolidation, Release 1.1 - US Realm';
UPDATE openchpl.test_standard SET "name" = 'HL7 Implementation Guide for CDA®Release 2: Consolidated CDA Templates for Clinical Notes (US Realm) Draft Standard for Trial Use, Volume 1 – Introductory Material, Release 2.1, August 2015
HL7 Implementation Guide for CDA® Release 2: Consolidated CDA Templates for Clinical Notes (US Realm), Draft Standard for Trial Use, Volume 2 – Templates and Supporting Material, Release 2.1, August 2015' WHERE "name" LIKE 'HL7 Implementation Guide for CDA®Release 2: Consolidated CDA Templates for Clinical Notes (US Realm) Draft Standard for Trial Use, Volume 1 – Introductory Material, Release 2.1, August 2015%';
UPDATE openchpl.test_standard SET "name" = 'HL7 Version 3 Implementation Guide: Data Segmentation for Privacy (DS4P), Release 1, Part 1: CDA R2 and Privacy Metadata Reusable Content Profile, May 16, 2014' WHERE "name" LIKE 'HL7 Version 3 Implementation Guide: Data Segmentation for Privacy (DS4P), Release 1, Part 1: CDA R2 and Privacy Metadata Reusable Content Profile, May 16, 2014';
UPDATE openchpl.test_standard SET "name" = 'HL7 CDA® Release 2 Implementation Guide: Quality Reporting Document Architecture – Category I(QRDA I); Release 1, DTSU Release 3 (US Realm), Volume 1 – Introductory Material, June 2015
HL7 CDA ® Release 2 Implementation Guide: Quality Reporting Document Architecture – Category I (QRDA I); Release 1, DSTU Release 3 (US Realm), Volume 2 – Templates and Supporting Material, June 2015' WHERE "name" LIKE 'HL7 CDA® Release 2 Implementation Guide: Quality Reporting Document Architecture – Category I(QRDA I); Release 1, DTSU Release 3 (US Realm), Volume 1 – Introductory Material, June 2015%';
UPDATE openchpl.test_standard SET "name" = 'Quality Reporting Document Architecture Category III, Implementation Guide for CDA Release 2' WHERE "name" LIKE 'Quality Reporting Document Architecture Category III, Implementation Guide for CDA Release 2';
UPDATE openchpl.test_standard SET "name" = 'Errata to the HL7 Implementation Guide for CDA® Release 2: Quality Reporting Document Architecture—Category III, DSTU Release 1 (US Realm), September 2014' WHERE "name" LIKE 'Errata to the HL7 Implementation Guide for CDA® Release 2: Quality Reporting Document Architecture—Category III, DSTU Release 1 (US Realm), September 2014';
UPDATE openchpl.test_standard SET "name" = 'HL7 2.5.1 Implementation Guide for Immunization Messaging Release 1.5, October 1, 2014
HL7 2.5.1 Implementation Guide for Immunization Messaging, Release 1.5 - Addendum, July 2015' WHERE "name" LIKE 'HL7 2.5.1 Implementation Guide for Immunization Messaging Release 1.5, October 1, 2014%';
UPDATE openchpl.test_standard SET "name" = 'HL7 Standard Code Set CVX—Vaccines Administered, updates through August 17, 2015' WHERE "name" LIKE 'HL7 Standard Code Set CVX—Vaccines Administered, updates through August 17, 2015';
UPDATE openchpl.test_standard SET "name" = 'PHIN Messaging Guide for Syndromic Surveillance: Emergency Department, Urgent Care, Inpatient and Ambulatory Care Settings, Release 2.0, April 21, 2015
Erratum to the CDC PHIN 2.0 Implementation Guide, August 2015; Erratum to the CDC PHIN 2.0 Messaging Guide, April 2015 Release for Syndromic Surveillance: Emergency Department, Urgent Care, Inpatient and Ambulatory Care Settings' WHERE "name" LIKE 'PHIN Messaging Guide for Syndromic Surveillance: Emergency Department, Urgent Care, Inpatient and Ambulatory Care Settings, Release 2.0, April 21, 2015%';
UPDATE openchpl.test_standard SET "name" = 'HL7 Version 2.5.1 Implementation Guide: Electronic Laboratory Reporting to Public Health, Release 1 (US Realm)
ELR 2.5.1 Clarification Document for EHR Technology Certification V1.1' WHERE "name" LIKE 'HL7 Version 2.5.1 Implementation Guide: Electronic Laboratory Reporting to Public Health, Release 1 (US Realm)%';
UPDATE openchpl.test_standard SET "name" = 'HL7 Implementation Guide for CDA©Release 2 Implementation Guide: Reporting to Public Health Cancer Registries from Ambulatory Healthcare Providers, Release 1; DSTU Release 1.1, Volume 1 – Introductory Material, April 2015
HL7 CDA© Release 2 Implementation Guide: Reporting to Public Health Cancer Registries from Ambulatory Healthcare Providers, Release 1; DSTU Release 1.1 (US Realm), Volume 2- Templates and Supporting Material, April 2015' WHERE "name" LIKE 'HL7 Implementation Guide for CDA©Release 2 Implementation Guide: Reporting to Public Health Cancer Registries from Ambulatory Healthcare Providers, Release 1; DSTU Release 1.1, Volume 1 – Introductory Material, April 2015%';
UPDATE openchpl.test_standard SET "name" = 'HL7 Implementation Guide for CDA®Release 2 – Level 3: Healthcare Associated Infection Reports, Release 1 - U.S. Realm, August 9, 2013' WHERE "name" LIKE 'HL7 Implementation Guide for CDA®Release 2 – Level 3: Healthcare Associated Infection Reports, Release 1 - U.S. Realm, August 9, 2013';
UPDATE openchpl.test_standard SET "name" = 'HL7 Implementation Guide for CDA Release 2: National Health Care Surveys (NHCS), Release 1 – US Realm, HL7 Draft Standard for Trial Use, Volume 1- Introductory Material, December 2014
HL7 Implementation Guide for CDA ®Release 2: National Health Care Surveys (NHCS), Release 1 – US Realm, HL7 Draft Standard for Trial Use, Volume 2 – Templates and Supporting Material, December 2014' WHERE "name" LIKE 'HL7 Implementation Guide for CDA Release 2: National Health Care Surveys (NHCS), Release 1 – US Realm, HL7 Draft Standard for Trial Use, Volume 1- Introductory Material, December 2014%';
UPDATE openchpl.test_standard SET "name" = 'ITU-TE.123, Series E: Overall Network Operation, Telephone Service, Service Operation and Human Factors, International operation – General provisions concerning users: Notation for national and international telephone numbers, e-mail addresses and web addresses, February 2001
ITU-T E. 164, Series E: Overall Network Operation, Telephone Service, Service Operation and Human Factors, International Operation - Numbering plan of the international telephone service: The international public telecommunication numbering plan, November 2010' WHERE "name" LIKE 'ITU-TE.123, Series E: Overall Network Operation, Telephone Service, Service Operation and Human Factors, International operation – General provisions concerning users: Notation for national and international telephone numbers, e-mail addresses and web addresses, February 2001%';
UPDATE openchpl.test_standard SET "name" = 'Request for Comments (RFC) 5905:Network Time Protocol Version 4: Protocol and Algorithms Specification, June 2010' WHERE "name" LIKE 'Request for Comments (RFC) 5905:Network Time Protocol Version 4: Protocol and Algorithms Specification, June 2010';
UPDATE openchpl.test_standard SET "name" = 'Request for Comments (RFC) 5646, "Tags for Identifying Languages," September 2009, copyright 2009' WHERE "name" LIKE 'Request for Comments (RFC) 5646, "Tags for Identifying Languages," September 2009, copyright 2009';
UPDATE openchpl.test_standard SET "name" = 'SCRIPT Standard, Version 10.6, October, 2008' WHERE "name" LIKE 'SCRIPT Standard, Version 10.6, October, 2008';
UPDATE openchpl.test_standard SET "name" = 'Annex A: Federal Information Processing Standards (FIPS) Publication 140-2, Security Requirements for Cryptographic Modules, October 8, 2014' WHERE "name" LIKE 'Annex A: Federal Information Processing Standards (FIPS) Publication 140-2, Security Requirements for Cryptographic Modules, October 8, 2014';
UPDATE openchpl.test_standard SET "name" = 'FIPS PUB 180-4, Secure Hash Standard, 180-4 (August 2015)' WHERE "name" LIKE 'FIPS PUB 180-4, Secure Hash Standard, 180-4 (August 2015)';
UPDATE openchpl.test_standard SET "name" = 'The Office of Management and Budget Standards for Maintaining, Collecting, and Presenting Federal Data on Race and Ethnicity, Statistical Policy Directive No. 15, as revised, October 30, 1997' WHERE "name" LIKE 'The Office of Management and Budget Standards for Maintaining, Collecting, and Presenting Federal Data on Race and Ethnicity, Statistical Policy Directive No. 15, as revised, October 30, 1997';
UPDATE openchpl.test_standard SET "name" = 'Public Health Data Standards Consortium Source of Payment Typology Code Set Version 5.0 (October 2011)' WHERE "name" LIKE 'Public Health Data Standards Consortium Source of Payment Typology Code Set Version 5.0 (October 2011)';
UPDATE openchpl.test_standard SET "name" = 'Logical Observation Identifiers Names and Codes (LOINC®) Database version 2.40' WHERE "name" LIKE 'Logical Observation Identifiers Names and Codes (LOINC®) Database version 2.40';
UPDATE openchpl.test_standard SET "name" = 'Logical Observation Identifiers Names and Codes (LOINC®) Database version 2.52, Released June 2015' WHERE "name" LIKE 'Logical Observation Identifiers Names and Codes (LOINC®) Database version 2.52, Released June 2015';
UPDATE openchpl.test_standard SET "name" = 'The Unified Code of Units of Measure, Revision 1.9, October 23, 2013' WHERE "name" LIKE 'The Unified Code of Units of Measure, Revision 1.9, October 23, 2013';
UPDATE openchpl.test_standard SET "name" = 'Applicability Statement for Secure Health Transport, Version 1.2, August 2015' WHERE "name" LIKE 'Applicability Statement for Secure Health Transport, Version 1.2, August 2015';
UPDATE openchpl.test_standard SET "name" = 'XDR and XDM for Direct Messaging Specification, Version 1, March 9, 2011' WHERE "name" LIKE 'XDR and XDM for Direct Messaging Specification, Version 1, March 9, 2011';
UPDATE openchpl.test_standard SET "name" = 'Implementation Guide for Direct Edge Protocols, Version 1.1, June 25, 2014' WHERE "name" LIKE 'Implementation Guide for Direct Edge Protocols, Version 1.1, June 25, 2014';
UPDATE openchpl.test_standard SET "name" = 'Implementation Guide for Delivery Notification in Direct, Version 1.0, June 29, 2012' WHERE "name" LIKE 'Implementation Guide for Delivery Notification in Direct, Version 1.0, June 29, 2012';
UPDATE openchpl.test_standard SET "name" = 'International Health Terminology Standards Development Organisation (IHTSDO) SNOMED CT® International Release July 2012 and US Extension to SNOMED CT® March 2012 Release' WHERE "name" LIKE 'International Health Terminology Standards Development Organisation (IHTSDO) SNOMED CT® International Release July 2012 and US Extension to SNOMED CT® March 2012 Release';
UPDATE openchpl.test_standard SET "name" = 'International Health Terminology Standards Development Organisation (IHTSDO) Systematized Nomenclature of Medicine Clinical Terms (SNOMED CT®), U.S. Edition, September 2015 Release' WHERE "name" LIKE 'International Health Terminology Standards Development Organisation (IHTSDO) Systematized Nomenclature of Medicine Clinical Terms (SNOMED CT®), U.S. Edition, September 2015 Release';
UPDATE openchpl.test_standard SET "name" = 'International Health Terminology Standards Development Organization (IHTSDO) Systematized Nomenclature of Medicine Clinical Terms (SNOMED CT®) U.S. Edition, September 2015 Release' WHERE "name" LIKE 'International Health Terminology Standards Development Organization (IHTSDO) Systematized Nomenclature of Medicine Clinical Terms (SNOMED CT®) U.S. Edition, September 2015 Release';
UPDATE openchpl.test_standard SET "name" = 'RxNorm, a standardized nomenclature for clinical drugs produced by the United States National Library of Medicine, September 8, 2015 Release' WHERE "name" LIKE 'RxNorm, a standardized nomenclature for clinical drugs produced by the United States National Library of Medicine, September 8, 2015 Release';
UPDATE openchpl.test_standard SET "name" = 'Web Content Accessibility Guidelines (WCAG) 2.0, Level A Conformance' WHERE "name" LIKE 'Web Content Accessibility Guidelines (WCAG) 2.0, Level A Conformance';
UPDATE openchpl.test_standard SET "name" = 'Web Content Accessibility Guidelines (WCAG) 2.0, Level AA Conformance' WHERE "name" LIKE 'Web Content Accessibility Guidelines (WCAG) 2.0, Level AA Conformance';
