-- Deployment file for version 20.11.3
--     as of 2022-01-24
-- ./changes/ocd-3800.sql
INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'POST', '/certified-products/pending/{pcpId:^-?\\d+$}/beta/confirm', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'POST'
	AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}/beta/confirm');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/details', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/details');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/{chplPrefix}-{identifier}/details', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/{chplPrefix}-{identifier}/details');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/{certifiedProductId:^-?\\d+$}/details', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/details');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'PUT', '/certified-products/{certifiedProductId}', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'PUT'
	AND api_operation = '/certified-products/{certifiedProductId}');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/{chplPrefix}-{identifier}', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/{chplPrefix}-{identifier}');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/{certifiedProductId:^-?\\d+$}', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/pending/{pcpId:^-?\\d+$}', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/pending', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/pending');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/ics_relationships', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/ics_relationships');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/{chplPrefix}-{identifier}/ics_relationships', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/{chplPrefix}-{identifier}/ics_relationships');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/{certifiedProductId:^-?\\d+$}/ics_relationships', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/ics_relationships');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/certified-products/pending/metadata', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/certified-products/pending/metadata');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/change-requests', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/change-requests');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/change-requests/{changeRequestId}', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/change-requests/{changeRequestId}');


INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'PUT', '/change-requests', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'PUT'
	AND api_operation = '/change-requests');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'POST', '/change-requests', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'POST'
	AND api_operation = '/change-requests');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/developers', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/developers');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/developers/{developerId}', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/developers');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'PUT', '/developers/{developerId}', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'PUT'
	AND api_operation = '/developers');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/developers/{developerId}/hierarchy', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/developers/{developerId}/hierarchy');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/products', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/products');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'GET', '/products/{productId}', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'GET'
	AND api_operation = '/products/{productId}');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'PUT', '/products', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'PUT'
	AND api_operation = '/products');

INSERT INTO openchpl.deprecated_response_field_api (http_method, api_operation, last_modified_user)
SELECT 'POST', '/products/{productId}/split', -1
WHERE NOT EXISTS (SELECT * 
	FROM openchpl.deprecated_response_field_api
	WHERE http_method = 'POST'
	AND api_operation = '/products/{productId}/split');

INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}/beta/confirm' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}/beta/confirm')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}/beta/confirm' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}/beta/confirm')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}/beta/confirm' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}/beta/confirm')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}/beta/confirm' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}/beta/confirm')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/details' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/details')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/certified-products/{certifiedProductId}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/certified-products/{certifiedProductId}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/certified-products/{certifiedProductId}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/certified-products/{certifiedProductId}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/certified-products/{certifiedProductId}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/certified-products/{certifiedProductId}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/certified-products/{certifiedProductId}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/certified-products/{certifiedProductId}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/listings/pending/{id}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/listings/pending/{id}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/listings/pending/{id}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/listings/pending/{id}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/listings/pending/{id}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/listings/pending/{id}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/listings/pending/{id}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/listings/pending/{id}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/{pcpId:^-?\\d+$}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/ics_relationships' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/ics_relationships')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/ics_relationships' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/ics_relationships')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/ics_relationships' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{year}.{testingLab}.{certBody}.{vendorCode}.{productCode}.{versionCode}.{icsCode}.{addlSoftwareCode}.{certDateCode}/ics_relationships')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/ics_relationships' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/ics_relationships')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/ics_relationships' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/ics_relationships')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/ics_relationships' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{chplPrefix}-{identifier}/ics_relationships')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/ics_relationships' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/ics_relationships')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/ics_relationships' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/ics_relationships')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/ics_relationships' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/{certifiedProductId:^-?\\d+$}/ics_relationships')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/metadata' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/metadata')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/metadata' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/metadata')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'product -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/metadata' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/certified-products/pending/metadata')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/change-requests' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/change-requests')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/change-requests/{changeRequestId}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/change-requests/{changeRequestId}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/change-requests' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/change-requests')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'results -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/change-requests' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/change-requests')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'developers -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/developers' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/developers')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/developers/{developerId}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/developers/{developerId}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestation', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/developers/{developerId}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/developers/{developerId}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/developers/{developerId}/hierarchy' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/developers/{developerId}/hierarchy')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'products -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/developers/{developerId}/hierarchy' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/developers/{developerId}/hierarchy')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'products -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/developers/{developerId}/hierarchy' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/developers/{developerId}/hierarchy')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'products -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/products' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/products')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'products -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/products' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/products')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/products/{productId}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/products/{productId}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/products/{productId}' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'GET' AND api_operation = '/products/{productId}')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/products' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/products')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/products' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'PUT' AND api_operation = '/products')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'oldProduct -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/products/{productId}/split' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/products/{productId}/split')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'oldProduct -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/products/{productId}/split' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/products/{productId}/split')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'newProduct -> owner -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/products/{productId}/split' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/products/{productId}/split')); 
INSERT INTO openchpl.deprecated_response_field (deprecated_api_id, response_field, removal_date, change_description, last_modified_user) SELECT deprecated_response_field_api.id, 'newProduct -> ownerHistory -> developer -> transparencyAttestations', '2022-03-01', 'This field is deprecated and will be removed from the response data in a future release.', -1 FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/products/{productId}/split' AND NOT EXISTS (SELECT *  FROM openchpl.deprecated_response_field WHERE response_field = 'transparencyAttestation' AND removal_date = '2022-03-01' AND change_description = 'This field is deprecated and will be removed from the response data in a future release.' AND deprecated_api_id = (SELECT id FROM openchpl.deprecated_response_field_api WHERE http_method = 'POST' AND api_operation = '/products/{productId}/split')); 
;
insert into openchpl.data_model_version (version, deploy_date, last_modified_user) values ('20.11.3', '2022-01-24', -1);
\i dev/openchpl_soft-delete.sql
\i dev/openchpl_views.sql
\i dev/openchpl_grant-all.sql
