alter table openchpl.certified_product rename transparency_attestation_url to mandatory_disclosures;
alter table openchpl.pending_certified_product rename vendor_transparency_attestation_url to vendor_mandatory_disclosures;
