alter table openchpl.quarterly_report rename reactive_summary to reactive_surveillance_summary;
alter table openchpl.quarterly_report rename transparency_disclosure_summary to disclosure_requirements_summary;
