ALTER TABLE openchpl.change_request_attestation_submission_response
DROP COLUMN IF EXISTS response_message;

ALTER TABLE openchpl.change_request_attestation_submission_response
ADD COLUMN response_message text;
