-- delete "developerCollection" cache from ehcache.xml ??
-- change email address for jira api key to alexandr or Chai CSrinadhu@ainq.com
-- /collections/developers looks like it needs the developer name and id
-- delete data from deprecated response field table
-- delete views 
-- delete tables
-- delete columns
-- delete transparency attestation type (note the name of that type was changed in attestations ticket)
